#!/usr/bin/env bash

set -u

. "/enstratus/bin/common_mod"

logTag="format"
LOGGER=/enstratus/bin/log

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ $# -lt 4 ] ; then
   $LOGGER -t "$logTag" Syntax: format DEVICE_ID FILE_SYSTEM MOUNT_POINT ENCRYPTED
   exit 1
fi

deviceId=$1
fileSystem=$2
mountPoint=$3
encrypted=$4

$LOGGER -t "$logTag" format $@

el_ver=0
if [ -f /etc/redhat-release ]; then
	el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
fi
new_letter=$(echo ${deviceId:(-1)} | tr 'a-z' 'e-z')

if [[ $encrypted == "true" ]] ; then
	device=/dev/mapper/$deviceId
elif [ -b /dev/$deviceId ] ; then
	device=/dev/$deviceId
elif [ -b /dev/${deviceId/#sd/xvd} ] ; then
	device=/dev/${deviceId/#sd/xvd}
elif [[ $el_ver > 6.0 && ! -b /dev/$deviceId && -b /dev/xvd${new_letter} ]]; then
	device=/dev/xvd${new_letter}
else
	$LOGGER -t "$logTag" "Cannot find device ${deviceId}."
	exit 1
fi

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_with_pipe_value
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

[ -f /sbin/mkfs.${fileSystem} ] || ( $LOGGER -t "$logTag" "${fileSystem} not supported ; exit 24" )
case "$fileSystem" in
reiserfs)	yes | sudo /sbin/mkfs.${fileSystem} -f $device
			;;
*)			yes | sudo /sbin/mkfs.${fileSystem} $device
			;;
esac

if [ $? != 0 ] ; then
	exit 24
fi

distro=$(/enstratus/bin/getUnixOs)
mp=${mountPoint//\//\\\/}
sudo sed -i "/\s$mp\s/d" /etc/fstab
if [[ $encrypted == "true" ]] ; then
	if [ $distro == "UBUNTU" ]; then
		echo "$device $mountPoint $fileSystem noatime,nobootwait 0 0" | sudo tee -a /etc/fstab
	else
		echo "$device $mountPoint $fileSystem noatime 0 0" | sudo tee -a /etc/fstab
	fi
else
	if [ $distro == "UBUNTU" ]; then
		echo "$device $mountPoint $fileSystem defaults,nobootwait 0 0" | sudo tee -a /etc/fstab
	else
		echo "$device $mountPoint $fileSystem defaults 0 0" | sudo tee -a /etc/fstab
	fi
fi

if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

exit 0
