#!/usr/bin/env bash

serviceId=$1
remoteAddress=$2
remotePort=$3
HAPCFG=$4

# Check to see if the address is already listed in the haproxy.cfg
# If it does, just exit.

grep -q "${remoteAddress}" ${HAPCFG}

if [ $? == 0 ] ; then
    exit 0
fi

count=$( awk '/count/ {print $4}' ${HAPCFG})
incrementCount=$(( $count + 1 ))

sed "s/count = ${count}/count = ${incrementCount}/" -i ${HAPCFG}

echo "        server $serviceId-$incrementCount $remoteAddress:$remotePort cookie $serviceId-$incrementCount check" >> ${HAPCFG}
