#!/usr/bin/env bash

set -u
PATH=/bin:${PATH}

. "/enstratus/bin/common_mod"

logTag="mount"
LOGGER=/enstratus/bin/log

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ $# -lt 3 ] ; then
   $LOGGER -t "$logTag" Syntax: mount DEVICE_ID FILE_SYSTEM MOUNT_POINT
   exit 1
fi

deviceId=$1
fileSystem=$2
mountPoint=$3

$LOGGER -t "$logTag" mount "$@"

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@"  2>&1 | $LOGGER -t "$logTag"
	exit_with_pipe_value
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@"  2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

if [ ! -d "$mountPoint" ] ; then
	sudo mkdir "$mountPoint"
fi

# 1. Some kernels may detect sdX devices as xvdX
# 2. sdh is identified as xvdl since RHEL/CentOS 6.1
el_ver=0
distro=$(/enstratus/bin/getUnixOs)
if [ -f /etc/redhat-release ]; then
	el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
fi
new_letter=$(echo ${1:(-1)} | tr 'a-z' 'e-z')

if [ ! -b /dev/$1 ]; then
	if [[ -b /dev/${1/#sd/xvd} ]]; then
		deviceId=${1/#sd/xvd}
	elif [[ $el_ver > 6.0 && -b /dev/xvd${new_letter} ]]; then
		deviceId=xvd${new_letter}
	else
		$LOGGER -t "$logTag" "Cannot find device ${deviceId}."
		exit 1
	fi
fi

exists=$(grep " $mountPoint " /etc/fstab)

# nobootwait option is only needed in Ubuntu.
if [[ $exists == "" ]] && [[ $distro == "UBUNTU" ]]; then
	echo "/dev/$deviceId $mountPoint $fileSystem defaults,nobootwait 0 0" | sudo tee -a /etc/fstab
elif [[ $exists == "" ]]; then
	echo "/dev/$deviceId $mountPoint $fileSystem defaults 0 0" | sudo tee -a /etc/fstab
fi

sleep 10
sudo mount "$mountPoint" 2>&1 | $LOGGER -t "$logTag"
exit_if_pipe_false "Mount failed."
sudo chown enstratus:enstratus "$mountPoint"  2>&1 | $LOGGER -t "$logTag"
sudo chmod 775 "$mountPoint" 2>&1 | $LOGGER -t "$logTag"
ret=${PIPESTATUS}
				
if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
	ret=${PIPESTATUS}
fi

exit $ret
