#!/usr/bin/env bash

set -u
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/enstratus/bin

. "/enstratus/bin/common_mod"

logTag="openEncryption"
LOGGER=/enstratus/bin/log

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ $# -lt 3 ] ; then
   $LOGGER -t "$logTag" Syntax: openEncryption RAW_DEVICE ENCRYPTED_DEVICE KEY_FILE
   exit 1
fi

if ! sudo which cryptsetup ; then
	$LOGGER -t "$logTag" cryptsetup not installed
	exit 2
fi

rawDevice=$1
encryptedDevice=$2
keyFile=$3

$LOGGER -t "$logTag" openEncryption "$@"

if [ -e /dev/mapper/temp*  ]; then
        sudo rm -f /dev/mapper/temp*
fi

if [ ! -f "$keyFile" ] ; then
        $LOGGER -t "$logTag" Unable to ready key file
        exit 10
fi

if [ -x ${CUSTOM} ] ; then
        ${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_with_pipe_value
fi

if [ -x ${CUSTOM}-pre ] ; then
        ${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

# 1. Some kernels may detect sdX devices as xvdX
# 2. sdh is identified as xvdl since RHEL/CentOS 6.1
el_ver=0
if [ -f /etc/redhat-release ]; then
	el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
fi
new_letter=$(echo ${1:(-1)} | tr 'a-z' 'e-z')

if [ ! -b /dev/$1 ]; then
	if [[ -b /dev/${1/#sd/xvd} ]]; then
		rawDevice=${1/#sd/xvd}
	elif [[ $el_ver > 6.0 && -b /dev/xvd${new_letter} ]]; then
		rawDevice=xvd${new_letter}
	else
		$LOGGER -t "$logTag" "Cannot find device ${rawDevice}."
		exit 1
	fi
fi

sudo cryptsetup --key-file $keyFile -q luksOpen "/dev/$rawDevice" $encryptedDevice > /dev/null 2>&1

if [ $? != 0 ] ; then
        $LOGGER -t "$logTag" Unable to open encrypted device.
        exit 11
fi

if [ -x ${CUSTOM}-post ] ; then
        ${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

exit 0
