#!/bin/sh


case "$1" in
    configure)

	DIR=/opt/dcm-agent-extras/ossec
	GROUP="ossec"
	USER="ossec"
	USERM="ossecm"
	USERR="ossecr"
	OSMYSHELL=/bin/false

    set -e
	if ! getent group | grep -q "^${GROUP}:"
	then
		groupadd --system ${GROUP}
	fi

	if ! getent passwd | grep -q "^${USER}:"
	then
		useradd -d ${DIR} -s ${OSMYSHELL} -g ${GROUP} ${USER}
	fi

	# create the mail group
	if ! getent passwd | grep -q "^${USERM}:"
	then
		useradd -d ${DIR} -s ${OSMYSHELL} -g ${GROUP} ${USERM}
	fi
	if ! getent passwd | grep -q "^${USERR}:"
	then
		useradd -d ${DIR} -s ${OSMYSHELL} -g ${GROUP} ${USERR}
	fi

	# Default for all directories
	chmod -R 550 ${DIR}
	chown -R root:${GROUP} ${DIR}

	# To the ossec queue (default for agentd to read)
	chown -R ${USER}:${GROUP} ${DIR}/queue
	chmod -R 750 ${DIR}/queue
	chmod 550 ${DIR}/queue
	chmod 770 ${DIR}/queue/alerts
	chmod 770 ${DIR}/queue/ossec

	# For the logging user
	chown -R ${USER}:${GROUP} ${DIR}/logs
	chmod -R 750 ${DIR}/logs
	chmod -R 775 ${DIR}/queue/rids
	touch ${DIR}/logs/ossec.log
	chown ${USER}:${GROUP} ${DIR}/logs/ossec.log
	chmod 664 ${DIR}/logs/ossec.log

    chown -R ${USER}:${GROUP} ${DIR}/queue/diff
    chmod -R 750 ${DIR}/queue/diff
    chmod 740 ${DIR}/queue/diff/* > /dev/null 2>&1 || true

    # For the etc dir
	chmod 550 ${DIR}/etc
	chown -R root:${GROUP} ${DIR}/etc
	if [ -f /etc/localtime ]; then
	    cp -pL /etc/localtime ${DIR}/etc/;
	    chmod 555 ${DIR}/etc/localtime
	    chown root:${GROUP} ${DIR}/etc/localtime
	fi

	if [ -f /etc/TIMEZONE ]; then
	    cp -p /etc/TIMEZONE ${DIR}/etc/;
	    chmod 555 ${DIR}/etc/TIMEZONE
	fi

	# More files
	chown root:${GROUP} ${DIR}/etc/internal_options.conf
	chown root:${GROUP} ${DIR}/etc/local_internal_options.conf >/dev/null 2>&1 || true
	chown root:${GROUP} ${DIR}/etc/client.keys >/dev/null 2>&1 || true
	chown root:${GROUP} ${DIR}/agentless/*
	chown ${USER}:${GROUP} ${DIR}/.ssh
	chown root:${GROUP} ${DIR}/etc/shared/*

	chmod 550 ${DIR}/etc
	chmod 440 ${DIR}/etc/internal_options.conf
	chmod 440 ${DIR}/etc/local_internal_options.conf >/dev/null 2>&1 || true
	chmod 440 ${DIR}/etc/client.keys >/dev/null 2>&1 || true
	chmod 550 ${DIR}/agentless/*
	chmod 700 ${DIR}/.ssh
	chmod 770 ${DIR}/etc/shared
	chmod 440 ${DIR}/etc/shared/*

	# For the /var/run
	chmod 770 ${DIR}/var/run
	chown root:${GROUP} ${DIR}/var/run

	# For util.sh
	chown root:${GROUP} ${DIR}/bin/util.sh
	chmod +x ${DIR}/bin/util.sh

	# For binaries and active response
    chmod 755 ${DIR}/active-response/bin/*
    chown root:${GROUP} ${DIR}/active-response/bin/*
    chown root:${GROUP} ${DIR}/bin/*
    chmod 550 ${DIR}/bin/*

	# For ossec.conf
    chown root:${GROUP} ${DIR}/etc/ossec.conf
    chmod 440 ${DIR}/etc/ossec.conf

	chown ${USERR}:${GROUP} ${DIR}/queue/agent-info
	chown ${USERR}:${GROUP} ${DIR}/queue/rids

	# setup the dcm user so it can be added to ossec
	DCM_USERNAME=dcm
    grep -q "^$DCM_USERNAME:" /etc/group
    if [ $? != 0 ] ; then
        groupadd $DCM_USERNAME
        if [ $? != 0 ] ; then
            echo "Failed to add $DCM_USERNAME group."
            exit 40
        fi
    fi
    # Create user.
    id -u $DCM_USERNAME
    if [ $? != 0 ] ; then
        useradd -d $BASEDIRNAME/home -g $DCM_USERNAME -s /bin/false -m $DCM_USERNAME
        if [ $? != 0 ] ; then
            echo "Failed to add $DCM_USERNAME user."
            exit 41
        fi
    fi
    usermod -G $GROUP $DCM_USERNAME
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >22
        exit 1
    ;;
esac
