#!/bin/sh

set -e


case "$1" in
    configure)

	DIR=/opt/dcm-agent-extras/ossec
	GROUP="ossec"
	USER="ossec"
	GROUPM="ossecm"
	USERM="ossecm"
	OSMYSHELL=/sbin/nologin

	if ! getent group | grep -q "^${GROUP}:"
	then
		groupadd --system ${GROUP}
	fi
	if ! getent passwd | grep -q "^${USER}:"
	then
		useradd -d ${DIR} -s ${OSMYSHELL} -g ${GROUP} ${USER}
	fi

	# create the mail group
	if ! getent group | grep -q "^${GROUPM}:"
	then
		groupadd --system ${GROUPM}
	fi
	if ! getent passwd | grep -q "^${USERM}:"
	then
		useradd -d ${DIR} -s ${OSMYSHELL} -g ${GROUPM} ${USERM}
	fi

	mkdir -p ${DIR}/queue/ossec

    # Default for all directories
    chmod -R 550 ${DIR}
    chown -R root:${GROUP} ${DIR}

    # To the ossec queue (default for agentd to read)
    chown -R ${USER}:${GROUP} ${DIR}/queue/ossec
    chmod -R 770 ${DIR}/queue/ossec

    # For the logging user
    chown -R ${USER}:${GROUP} ${DIR}/logs
    chmod -R 750 ${DIR}/logs
    chmod -R 775 ${DIR}/queue/rids
    touch ${DIR}/logs/ossec.log
    chown ${USER}:${GROUP} ${DIR}/logs/ossec.log
    chmod 664 ${DIR}/logs/ossec.log

    chown -R ${USER}:${GROUP} ${DIR}/queue/diff
    chmod -R 750 ${DIR}/queue/diff
    chmod 740 ${DIR}/queue/diff/* 2>/dev/null || /bin/true

    # [...]
    # For the etc dir
    chmod 550 ${DIR}/etc
    chown -R root:${GROUP} ${DIR}/etc

    if [ -e /etc/localtime ]; then
            cp -p /etc/localtime ${DIR}/etc/;
    fi

    # [...]
    chown root:${GROUP} ${DIR}/etc/internal_options.conf 2> /dev/null || /bin/true
    chown root:${GROUP} ${DIR}/etc/local_internal_options.conf 2> /dev/null || /bin/true
    chown root:${GROUP} ${DIR}/etc/client.keys 2> /dev/null || /bin/true
    chown root:${GROUP} ${DIR}/agentless/*
    chown ${USER}:${GROUP} ${DIR}/.ssh
    chown -R root:${GROUP} ${DIR}/etc/shared

    chmod 550 ${DIR}/etc
    chmod 440 ${DIR}/etc/internal_options.conf
    chmod 440 ${DIR}/etc/local_internal_options.conf 2> /dev/null || /bin/true
    chmod 440 ${DIR}/etc/client.keys 2> /dev/null || /bin/true
    chmod -R 770 ${DIR}/etc/shared # ossec must be able to write to it
    chmod 550 ${DIR}/agentless/*
    chmod 700 ${DIR}/.ssh


    # For the /var/run
    chmod 770 ${DIR}/var/run
    chown root:${GROUP} ${DIR}/var/run

    # [...]
    chown root:${GROUP} ${DIR}/bin/util.sh
    chmod +x ${DIR}/bin/util.sh

    # [...]
    # active response
    chmod 755 ${DIR}/active-response/bin/*
    chown root:${GROUP} ${DIR}/active-response/bin/*

    chown root:${GROUP} ${DIR}/bin/*
    chmod 550 ${DIR}/bin/*

    # [...]
    chown root:${GROUP} ${DIR}/etc/ossec.conf
    chmod 440 ${DIR}/etc/ossec.conf

    /opt/dcm-agent-extras/ossec/bin/ossec-control enable client-syslog
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >22
        exit 1
    ;;
esac
