#!/bin/bash

set -u

LOGGER=/enstratus/bin/log
logTag="assembleRaid"

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

$LOGGER -t "$logTag" assembleRaid "$@"

args=($@)
deviceId=$1
devices=${args[@]:1}

deviceArray=($devices)
deviceCount=${#deviceArray[*]}

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
	exit $?
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
	if [ $? != 0 ] ; then
		exit $?
	fi
fi

sudo /sbin/modprobe md

map=""
for d in ${devices}; do
	map="${map} /dev/${d}"
done
yes | sudo /sbin/mdadm --assemble /dev/$deviceId $map
if [ $? != 0 ] ; then
	$LOGGER -t "$logTag" "Unable to create RAID with mdadm."
	exit 20
fi

if [ -f /etc/mdadm/mdadm.conf ] ; then
    sudo /sbin/mdadm --detail --scan | sudo tee -a /etc/mdadm/mdadm.conf
elif [ -f /etc/mdadm.conf ] ; then
    sudo /sbin/mdadm --detail --scan | sudo tee -a /etc/mdadm.conf
else
    sudo /sbin/mdadm --detail --scan | sudo tee /etc/mdadm.conf
fi

if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
fi

exit 0
