#!/bin/bash

set -u

logTag="format"
LOGGER=/enstratus/bin/log

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ $# -lt 4 ] ; then
   $LOGGER -t "$logTag" Syntax: format DEVICE_ID FILE_SYSTEM MOUNT_POINT ENCRYPTED
   exit 1
fi

deviceId=$1
fileSystem=$2
mountPoint=$3
encrypted=$4

$LOGGER format $1 $2 $3 $4

el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
new_letter=$(echo ${deviceId:(-1)} | tr 'a-z' 'e-z')

if [[ $encrypted == "true" ]] ; then
	device=/dev/mapper/$deviceId
elif [ -b /dev/$deviceId ] ; then
	device=/dev/$deviceId
elif [ -b /dev/${deviceId/#sd/xvd} ] ; then
	device=/dev/${deviceId/#sd/xvd}
elif [[ $el_ver > 6.0 && ! -b /dev/$deviceId && -b /dev/xvd${new_letter} ]]; then
	device=/dev/xvd${new_letter}
fi

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
	exit $?
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
	if [ $? != 0 ] ; then
		exit $?
	fi
fi

[ -f /sbin/mkfs.${fileSystem} ] || ( $LOGGER -t "$logTag" "${fileSystem} not supported ; exit 24" )
case "$fileSystem" in
reiserfs)	yes | sudo /sbin/mkfs.${fileSystem} -f $device
			;;
*)			yes | sudo /sbin/mkfs.${fileSystem} $device
			;;
esac

if [ $? != 0 ] ; then
	exit 24
fi


mp=${mountPoint//\//\\\/}
sudo sed -i "/\s$mp\s/d" /etc/fstab
if [[ $encrypted == "true" ]] ; then
	echo "$device $mountPoint $fileSystem noatime 0 0" | sudo tee -a /etc/fstab
else
	echo "$device $mountPoint $fileSystem defaults 0 0" | sudo tee -a /etc/fstab
fi

if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
fi

exit 0
