#!/usr/bin/env bash
#
# Copyright 2010-2013 Enstratius, Inc.
#
# post-install - Set privileges of directories and files, make init scripts, run enstratius service.
#
# This software is part of the Enstratius Cloud Management System. Only
# authorized licensees of Enstratius may use this software and only
# in the context of Enstratius-managed virtual servers and machine images.
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the Enstratius system as needed.

PATH=/usr/sbin:/bin:${PATH}

set -u

DCM_USERNAME="dcm"
BASEDIRNAME="/dcm"

needed_directories="$BASEDIRNAME $BASEDIRNAME/etc $BASEDIRNAME/bin $BASEDIRNAME/logs $BASEDIRNAME/home"
for d in $needed_directories
do
    echo "Creating directory at $d..."
    if [ ! -d $d ] ; then
	    mkdir -p $d
	    if [ $? != 0 ] ; then
		    echo "Could not create $d directory. Are you running this as root?"
            exit 30
	    fi
    fi
    echo "Done."
done

echo "Creating user and group..."
# Create user/group group.
grep -q "^$DCM_USERNAME:" /etc/group
if [ $? != 0 ] ; then
	groupadd $DCM_USERNAME
	if [ $? != 0 ] ; then
		echo "Failed to add $DCM_USERNAME group."
		exit 40
	fi
fi
# Create user.
id -u $DCM_USERNAME
if [ $? != 0 ] ; then
	useradd -d $BASEDIRNAME/home -g $DCM_USERNAME -s /bin/false -m $DCM_USERNAME
	if [ $? != 0 ] ; then
		echo "Failed to add $DCM_USERNAME user."
		exit 41
	fi
fi
echo "Done."
echo "Adding user to sudoers..."
# Update sudoers.
if [ -d /etc/sudoers.d ]; then
	# For distros that have the latest sudo package which uses sudoers.d directory.
	grep -q '#includedir /etc/sudoers.d' /etc/sudoers
	if [ $? -ne 0 ]; then
		echo "#includedir /etc/sudoers.d" >> /etc/sudoers
	fi
	sed -i "/$DCM_USERNAME/d" /etc/sudoers
	echo "Defaults:$DCM_USERNAME !requiretty" > /tmp/ens-sudoers
	echo "$DCM_USERNAME ALL=(ALL) NOPASSWD: ALL" >> /tmp/ens-sudoers
	chown root:root /tmp/ens-sudoers
	chmod 0440 /tmp/ens-sudoers
	mv /tmp/ens-sudoers /etc/sudoers.d/$DCM_USERNAME
elif [ -f /etc/sudoers ]; then
	# For distros that do not have the latest sudo package.
	chmod u+w /etc/sudoers
	sed -i "/$DCM_USERNAME/d" /etc/sudoers
	echo "Defaults:$DCM_USERNAME !requiretty" >> /etc/sudoers
	echo "$DCM_USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
	chmod u-w /etc/sudoers
else
	echo "error. sudoers not found."
	exit 55
fi
echo "Done."

echo "Attempting to install startup scripts..."

startup_fname="/etc/init.d/dcm-agent"
echo "#!/usr/bin/env bash" > $startup_fname

if [ -f /usr/sbin/update-rc.d ] ; then

	echo "#" >> $startup_fname
	echo "### BEGIN INIT INFO" >> $startup_fname
	echo "# Provides:          dcm-agent" >> $startup_fname
	echo "# Required-Start:    \$remote_fs \$syslog" >> $startup_fname
	echo "# Required-Stop:     \$remote_fs \$syslog" >> $startup_fname
	echo "# Should-Start:      \$network \$named" >> $startup_fname
	echo "# Should-Stop:       \$network \$named" >> $startup_fname
	echo "# Default-Start:     2 3 4 5" >> $startup_fname
	echo "# Default-Stop:      0 1 6" >> $startup_fname
	echo "# Short-Description: Starts and stops the enStratus agent" >> $startup_fname
	echo "# Description:       Starts and stops the enStratus agent" >> $startup_fname
	echo "### END INIT INFO" >> $startup_fname

    ln -s $BASEDIRNAME/bin/enstratiusinitd-DEB $BASEDIRNAME/bin/enstratiusinitd
elif [ -x /sbin/chkconfig ] ; then

	echo "# chkconfig: 2345 60 40" >> $startup_fname
	echo "# description: Manages the enStratus agent." >> $startup_fname

	ln -s $BASEDIRNAME/bin/enstratiusinitd-CENTOS $BASEDIRNAME/bin/enstratiusinitd
else
	echo "Could not identify startup protocols. Contact enStratus support at support@enstratus.com."
	exit 90
fi
echo "Done."

echo "env -i PATH=$PATH $BASEDIRNAME/bin/enstratiusinitd " '$@' >> $startup_fname
chmod 755 $startup_fname

echo "Create the configuration file"
/opt/dcm-agent/agentve/bin/dcm-agent-configure -v -I -U $DCM_USERNAME -p $BASEDIRNAME
if [ $? -ne 0 ]; then
    echo "The default configuration failed"
    exit 1
fi
echo "Done"

echo "======================================================="
echo "The installation of the DCM Agent has completed."
echo "To start the agent, run the following command."
echo "To configure the agent run $BASEDIRNAME/bin/dcm-configure.sh -i -r $BASEDIRNAME/etc/agent.conf"
echo "$startup_fname start"
echo "======================================================="
exit 0
