#!/bin/bash
#
# Perform necessary dcm-agent removal steps
# after package is uninstalled.
#

DCM_USERNAME="dcm"
BASEDIRNAME="/dcm"

rm -rf $BASEDIRNAME

deluser $DCM_USERNAME
delgroup $DCM_USERNAME

if [ -e /etc/sudoers.d/$DCM_USERNAME ]; then
    rm /etc/sudoers.d/$DCM_USERNAME
else
	sed -i "/$DCM_USERNAME/d" /etc/sudoers
fi

rm -f /etc/init.d/dcm-agent

echo "dcm-agent has been uninstalled!"

exit 0
