#!/usr/bin/env bash
# Copyright 2010-2013 Enstratius, Inc.
#
# pre-install - Set privileges of directories and files, make init scripts, run enstratius service.
# 
# This software is part of the Enstratius Cloud Management System. Only 
# authorized licensees of Enstratius may use this software and only
# in the context of Enstratius-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the Enstratius system as needed.

set -u

exit 0