#!/usr/bin/env bash

# Copyright 2011-2013 Enstratius, Inc.
#
# backupService - Makes a file system copy of the target service
# 
# This software is part of the Enstratius Cloud Management System. Only 
# authorized licensees of Enstratius may use this software and only
# in the context of Enstratius-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the Enstratius system as needed.
#
# FUNCTION
# Backs up the target service.
#

set -u
PATH=/usr/bin:${PATH}

. "/enstratus/bin/common_mod"

LOGGER=/enstratus/bin/log
logTag=enstratus:backupService

$LOGGER -t "$logTag" backupService "$@"

if [ $# -lt 2 ] ; then
   $LOGGER -t "$logTag" "Syntax: backupService SERVICE_ID FILE_PATH" 
   exit 1
fi

serviceId=$1
backupFile="$2"
BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ -x "$CUSTOM" ] ; then
	"$CUSTOM" "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_with_pipe_value
fi

if [ -x "${CUSTOM}-pre" ] ; then
	"${CUSTOM}-pre" "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

BACKUP="/mnt/services/$serviceId/bin/enstratus-backupService"

if [ -x "$BACKUP" ] ; then
	"$BACKUP" $serviceId $backupFile 2>&1 | $LOGGER -t "$logTag"
else 
	sudo zip -r -q $backupFile * 2>&1 | $LOGGER -t "$logTag"
fi

if [ -x "${CUSTOM}-post" ] ; then
	"${CUSTOM}-post" "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

exit 0
