#!/usr/bin/env bash

# This script is used to determine the "health" of a service. It is meant to be 
# user-extensible. The way to use this script is to write a script called
# enstratus-check and put it in the /bin directory of your service image.
# The Enstratius provisioning server will call this script during the launch
# of the service. If the script returns a code of "OK", the service will be
# marked as running. If not, it will be marked as impaired.

set -u

DIRNAME=`dirname $0`
LOGGER=$DIRNAME/log
logTag="checkService"

if [ $# -lt 1 ] ; then
   $LOGGER -t "$logTag" Syntax: checkService SERVICE_ID
   exit 1
fi

serviceId=$1

CHECK="/mnt/services/$serviceId/bin/enstratus-check"

if [ -x "$CHECK" ] ; then
	status=$("$CHECK" $serviceId)
	if [ $status -ne "OK" ] ; then
		$LOGGER -t "$logTag" $status
	fi
	echo $status
else
	echo "OK"
fi

exit 0
