#!/usr/bin/env bash

set -u
PATH=/bin:${PATH}

. "/enstratus/bin/common_mod"

logTag="unmount"
LOGGER=/enstratus/bin/log

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ $# -lt 1 ] ; then
   $LOGGER -t "$logTag" Syntax: unmount MOUNT_POINT
   exit 1
fi

mountPoint=$1

$LOGGER -t "$logTag" unmount "$@" 

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_with_pipe_value
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

sudo umount $mountPoint 2>&1 | $LOGGER -t "$logTag"
				
mp=${mountPoint//\//\\\/}
sudo sed -i "/\s$mp\s/d" /etc/fstab
				
if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

exit 0
