# -*- mode: ruby -*-
# vi: set ft=ruby :

# env vars for vb provider
$ES_STORAGE_CREDS = ENV['DCM_AGENT_STORAGE_CREDS'] || "null"
$DCM_AGENT_VERSION = ENV['DCM_AGENT_VERSION'] || "null"
$DCM_AGENT_PKG = ENV['AGENT_BASE_URL'] || "null"
$DCM_AGENT_TEST_LOCAL = ENV['DCM_AGENT_TEST_LOCAL'] || "null"

machine_config = {
  "aws" => {
    "default-ubuntu-1004-i386" => {
      :hostname => "ubuntu-1004-i386",
      :box => "default-ubuntu-1004-i386",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-10e41778",
      :ssh_username => "ubuntu"
      },
    "default-ubuntu-1004" => {
      :hostname => "ubuntu-1004",
      :box => "default-ubuntu-1004",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-0baf7662",
      :ssh_username => "ubuntu"
      },
    "default-ubuntu-1204" => {
      :hostname => "ubuntu-1204",
      :box => "default-ubuntu-1204",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-fd20ad94",
      :ssh_username => "ubuntu"
      },
    "default-ubuntu-1204-i386" => {
      :hostname => "ubuntu-1204-i386",
      :box => "default-ubuntu-1204-i386",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-f87dba90",
      :ssh_username => "ubuntu"
      },
    "default-ubuntu-1404" => {
      :hostname => "ubuntu-1404",
      :box => "default-ubuntu-1404",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-864d84ee",
      :ssh_username => "ubuntu"
      },
    "default-ubuntu-1404-i386" => {
      :hostname => "ubuntu-1404-i386",
      :box => "default-ubuntu-1404-i386",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-384d8450",
      :ssh_username => "ubuntu"
      },
    "default-debian-6.0" => {
      :hostname => "debian-6.0",
      :box => "default-debian-6.0",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-e00df089",
      :ssh_username => "root"
      },
    "default-debian-6.0-i386" => {
      :hostname => "debian-6.0-i386",
      :box => "default-debian-6.0-i386",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-386ed551",
      :ssh_username => "root"
      },
    "default-debian-7.6" => {
      :hostname => "debian-7.6",
      :box => "default-debian-7.6",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-2c886c44",
      :ssh_username => "admin"
      },
    "default-debian-7.6-i386" => {
      :hostname => "debian-7.6-i386",
      :box => "default-debian-7.6-i386",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-90886cf8",
      :ssh_username => "admin"
      },
    "default-centos-65-i386" => {
      :hostname => "centos-65-i386",
      :box => "default-centos-65-i386",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-3e6d8856",
      :ssh_username => "admin"
      },
    "default-centos-64" => {
      :hostname => "centos-64",
      :box => "default-centos-64",
      :box_url => "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box",
      :instance_type => "m1.medium",
      :ami => "ami-3f3e4856",
      :ssh_username => "admin"
      }
  },

  "vb" => {
    "default-ubuntu-1004-i386" => {
      :hostname => "ubuntu-1004-i386",
      :box => "opscode-ubuntu-10.04-i386",
      :box_url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04-i386_chef-provisionerless.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/ubuntu-1004-i386.disk"
      },
    "default-ubuntu-1004" => {
      :hostname => "ubuntu-1004",
      :box => "opscode-ubuntu-10.04",
      :box_url => "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04_chef-provisionerless.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/ubuntu-1004.disk"
      },
    'default-ubuntu-1204' => {
      :hostname => "ubuntu-1204",
      :box => "opscode-ubuntu-12.04",
      :box_url => "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/ubuntu-1204.disk"
      },
    'default-ubuntu-1204-i386' => {
      :hostname => "ubuntu-1204-i386",
      :box => "opscode-ubuntu-12.04-i386",
      :box_url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10-i386_chef-provisionerless.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/ubuntu-1204-i386.disk"
      },
    'default-ubuntu-1404' => {
      :hostname => "ubuntu-1404",
      :box => "opscode-ubuntu-14.04",
      :box_url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/ubuntu-1404.disk"
      },
    'default-ubuntu-1404-i386' => {
      :hostname => "ubuntu-1404-i386",
      :box => "default-ubuntu-14.04-i386",
      :box_url => "https://s3.amazonaws.com/dcmagentboxes/default-ubuntu-1404-i386.agent.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/ubuntu-1404-i386.disk"
      },
    'default-debian-608' => {
      :hostname => "debian-608",
      :box => "default-debian-608",
      :box_url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8_chef-provisionerless.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/default-debian-608.disk"
      },
    'default-debian-608-i386' => {
      :hostname => "debian-608-i386",
      :box => "default-debian-608-i386",
      :box_url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8-i386_chef-provisionerless.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/default-debian-608-i386.disk"
      },
    'default-debian-75' => {
      :hostname => "debian-75",
      :box => "default-debian-75",
      :box_url => "https://vagrantcloud.com/ffuenf/debian-7.5.0-amd64/version/5/provider/virtualbox.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/default-debian-75.disk"
      },
    'default-debian-75-i386' => {
      :hostname => "debian-75-i386",
      :box => "default-debian-75-i386",
      :box_url => "https://vagrantcloud.com/remram/debian-7.5-i386/version/1/provider/virtualbox.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/default-debian-75-i386.disk"
      },
    'default-centos-65-i386' => {
      :hostname => "centos-65-i386",
      :box => "opscode-centos-6.5-i386",
      :box_url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5-i386_chef-provisionerless.box",
      :second_controller => "IDE Controller",
      :disk_path => "/tmp/centos-64-i386.disk"
      }
  }
}

def need_privilege(machine_name)
  if machine_name == 'default-debian-6.0'
    return false
  else
    return true
  end
end

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  prov_switch = ENV['DCM_AGENT_TEST_PROVISIONER']

  if prov_switch == "aws"
    config.vm.synced_folder ".", "/vagrant", disabled: true
  elsif prov_switch == "vb"
    config.vm.synced_folder "../bin/", "/agent/bin"
    config.vm.synced_folder "../src/", "/agent/src"
    vagrant_root = File.dirname(__FILE__)
    vagrant_root = File.dirname(vagrant_root)
    config.vm.synced_folder "../", vagrant_root
  else
     puts 'You have to set DCM_AGENT_TEST_PROVISIONER to vb or aws'
     exit
  end

  machine_map = machine_config[prov_switch]

  machine_map.each do |key, value|
    machine_name = key
    machine_values = value
    config.vm.box_url = machine_values[:box_url]
    config.vm.hostname = machine_values[:hostname]
    config.vm.box = machine_values[:box]

    if prov_switch == "aws"
      config.vm.define machine_name do |vm_config|

        vm_config.vm.provider :aws do |aws, override|
          aws.access_key_id = ENV['AWS_ACCESS_KEY']
          aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
          aws.keypair_name = ENV['AWS_KEYPAIR_NAME']
          aws.instance_type = machine_values[:instance_type]
          aws.ami = machine_values[:ami]
          override.ssh.username = machine_values[:ssh_username]
          override.ssh.private_key_path = ENV['AWS_PRIVATE_KEYPAIR_PATH']
        end
        vm_config.vm.provision :shell do |mk|
          mk.privileged = need_privilege(machine_name)
          mk.inline = 'mkdir /prov &&
                       chmod -R 777 /prov'
        end

        vm_config.vm.provision :file do |file|
          file.source = "envs" # environment variables
          file.destination = "/prov/envs"
        end

        vm_config.vm.provision :file do |file|
          file.source = "creds" #storage provider creds
          file.destination = "/prov/creds"
        end

        vm_config.vm.provision :shell do |mc|
          mc.privileged = need_privilege(machine_name)
          mc.path = "install_agent_test.sh"
        end

      end
    else
      config.vm.define machine_name do |vm_config|
        vm_config.vm.provider :virtualbox do |v|
          v.customize [ "createhd", "--filename", machine_values[:disk_path], "--size", 1000 ]
          v.customize ['storageattach', :id, '--storagectl', machine_values[:second_controller], '--port', 1, '--device', 0, '--type', 'hdd', '--medium',machine_values[:disk_path]]
          v.memory = 2048
        end

        vm_config.vm.provision :shell do |shell|
          shell.inline = "sudo /vagrant/test-distro.sh $1 $2 $3"
          shell.args = ["#$ES_STORAGE_CREDS", "#$DCM_AGENT_PKG", "#$DCM_AGENT_VERSION" "#$DCM_AGENT_TEST_LOCAL"]
        end
      end
    end
  end
end
