Vagrant.configure("2") do |config|

  config.vm.synced_folder "../bin/", "/agent/bin"
  config.vm.synced_folder "../pkg/", "/agent/pkgs"
  config.vm.synced_folder "../src/", "/agent/src"
  vagrant_root = File.dirname(__FILE__)
  vagrant_root = File.dirname(vagrant_root)
  config.vm.synced_folder "../", vagrant_root

  $ES_STORAGE_CREDS = ENV['DCM_AGENT_STORAGE_CREDS']

  config.vm.define 'default-ubuntu-1004-i386' do |c|
    c.vm.hostname="ubuntu-1004-i386"
    c.vm.box = "opscode-ubuntu-10.04-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04-i386_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/ubuntu-1004-i386.disk"
  end

  config.vm.define 'default-ubuntu-1004' do |c|
    c.vm.hostname="ubuntu-1004"
    c.vm.box = "opscode-ubuntu-10.04"
    c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/ubuntu-1004.disk"
  end

  config.vm.define 'default-ubuntu-1204' do |c|
    c.vm.hostname="ubuntu-1204"
    c.vm.box = "opscode-ubuntu-12.04"
    c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/ubuntu-1204.disk"
  end

  config.vm.define 'default-ubuntu-1204-i386' do |c|
    c.vm.hostname="ubuntu-1204-i386"
    c.vm.box = "opscode-ubuntu-12.04-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10-i386_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/ubuntu-1204-i386.disk"
  end

  config.vm.define 'default-ubuntu-1404' do |c|
    c.vm.hostname="ubuntu-1404"
    c.vm.box = "opscode-ubuntu-14.04"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/ubuntu-1404.disk"
  end

  config.vm.define 'default-ubuntu-1404-i386' do |c|
    c.vm.hostname="ubuntu-1404-i386"
    c.vm.box = "default-ubuntu-14.04-i386"
    c.vm.box_url = "https://s3.amazonaws.com/dcmagentboxes/default-ubuntu-1404-i386.agent.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/ubuntu-1404-i386.disk"
  end

  config.vm.define 'default-ubuntu-1310' do |c|
    c.vm.hostname="ubuntu-1310"
    c.vm.box = "opscode-ubuntu-13.10"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/ubuntu-1310.disk"
  end

  config.vm.define 'default-ubuntu-1310-i386' do |c|
    c.vm.hostname="ubuntu-1310-i386"
    c.vm.box = "default-ubuntu-13.10-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10-i386_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/ubuntu-1310-i386.disk"
  end

  config.vm.define 'default-debian-608' do |c|
    c.vm.hostname="default-debian-608"
    c.vm.box = "default-debian-608"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/default-debian-608.disk"
  end

  config.vm.define 'default-debian-608-i386' do |c|
    c.vm.hostname="default-debian-608-i386"
    c.vm.box = "default-debian-608-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8-i386_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/default-debian-608-i386.disk"
  end

  config.vm.define 'default-debian-720' do |c|
    c.vm.hostname="default-debian-720"
    c.vm.box = "default-debian-720"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/default-debian-720.disk"
  end

  config.vm.define 'default-debian-720-i386' do |c|
    c.vm.hostname="default-debian-720-i386"
    c.vm.box = "default-debian-720-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0-i386_chef-provisionerless.box"

    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/default-debian-720-i386.disk"
  end

  config.vm.define 'default-centos-65-i386' do |c|
    c.vm.box = "opscode-centos-6.5-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5-i386_chef-provisionerless.box"
 
    $ES_SECOND_CONTROLLER = "IDE Controller"
    $ES_DISK_PATH = "/tmp/ubuntu-1404-i386.disk"
  end

  config.vm.provider "virtualbox" do |v|
    v.customize [ "createhd", "--filename", "#$ES_DISK_PATH", "--size", 1000 ]
    v.customize ['storageattach', :id, '--storagectl', "#$ES_SECOND_CONTROLLER", '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "#$ES_DISK_PATH"]
    v.memory = 1024
  end

  config.vm.provision :shell do |shell|
    shell.inline = "/vagrant/test-distro.sh $1"
    shell.args = ["#$ES_STORAGE_CREDS"]
  end
end
