#!/bin/bash

set -u

LOGGER=/enstratus/bin/log
logTag="haproxy:startProxy"

$LOGGER -t "$logTag" startProxy "$@"

service=$1
primaryName=$2
secondaryNames=$3
ipAddress=$4
remoteAddress=$5
remotePort=$6

if [ $# -gt 6 ] ; then
sslCert=$7
sslKey=$8
if [ $# -gt 8 ] ; then
sslChained=$9
fi 
fi

APACHE=/etc/apache2

if [ ! -d "$APACHE/ssl" ] ; then
sudo mkdir "$APACHE/ssl"
sudo chmod 700 "$APACHE/ssl"
fi

if [ $# -gt 6 ] ; then
	if [ $remotePort -eq "443" ] ; then
		remotePort=80
	fi
	sudo mv "$sslCert" "$APACHE/ssl/$service.cert"
	sslCert="$APACHE/ssl/$service.cert"
	sudo mv "$sslKey" "$APACHE/ssl/$service.key"
	sslKey="$APACHE/ssl/$service.key"
	sudo chmod 440 "$sslKey"
	if [ $# -gt 8 ] ; then 
		sudo mv "$sslChained" "$APACHE/ssl/$service.chain"
	sslChained="$APACHE/ssl/$service.chain"
	fi
fi

if [ ! -f /usr/bin/cronolog ]; then
		$LOGGER -t "$logTag" cronolog is not installed. Exiting
		exit 20
fi

if [ ! -d /mnt/services/$service/log ]; then
	sudo mkdir -p /mnt/services/$service/log
	sudo chmod 0750 /mnt/services/$service/log
fi

# Apache mod_proxy and mod_proxy_http must be enable for reverseproxy
for mod in proxy proxy_http proxy_html ssl
do
	sudo a2enmod $mod
	ret=$?
	if [ $ret -ne 0 ] ; then
		$LOGGER -t "$logTag" Apache $mod could not be enabled
		exit 20
	fi
done

confFile="${APACHE}/httpd.conf"
sudo touch $confFile

if [ ! -f "${confFile}-setup" ] ; then
echo "ServerName ${ipAddress}" | sudo tee "$confFile"
echo "NameVirtualHost ${ipAddress}:80" | sudo tee -a "$confFile"
echo "NameVirtualHost ${ipAddress}:443" | sudo tee -a "$confFile"
sudo touch "${confFile}-setup"
fi

siteFile="${APACHE}/sites-available/${service}.conf"

echo "<VirtualHost ${ipAddress}:80>" | sudo tee "$siteFile"
echo "    ServerName $primaryName" | sudo tee -a "$siteFile"
if [ "$secondaryNames" != "NONE" ] ; then
	aliases=$(echo "$secondaryNames" | tr -s ',' ' ')
	for alias in $aliases ; do
		echo "    ServerAlias $alias" | sudo tee -a "$siteFile"
	done 
fi
echo ""  | sudo tee -a "$siteFile"

echo "    CustomLog \"|/usr/bin/cronolog /mnt/services/${service}/log/access-%Y-%m.log\" common" | sudo tee -a "$siteFile"
echo "    ErrorLog \"|/usr/bin/cronolog /mnt/services/${service}/log/error-%Y-%m.log\"" | sudo tee -a "$siteFile"
echo "    ProxyRequests Off" | sudo tee -a "$siteFile"
echo "    ProxyPreserveHost On" | sudo tee -a "$siteFile"
echo "    ProxyPass / http://localhost:8080/" | sudo tee -a "$siteFile"
echo "    <Proxy *>" | sudo tee -a "$siteFile"
echo "        Order deny,allow" | sudo tee -a "$siteFile"
echo "        Allow from all" | sudo tee -a "$siteFile"
echo "    </Proxy>" | sudo tee -a "$siteFile"
echo "</VirtualHost>" | sudo tee -a "$siteFile"

sslFile="${APACHE}/sites-available/${service}-ssl.conf"

if [ $# -gt 6 ] ; then
	echo "<VirtualHost ${ipAddress}:443>" | sudo tee "$sslFile"
	echo "    ServerName $primaryName" | sudo tee -a "$sslFile"

	if [ $secondaryNames != "NONE" ] ; then
		aliases=$(echo $secondaryNames | tr -s ',' ' ')
		for alias in $aliases ; do
			echo "    ServerAlias $alias" | sudo tee -a "$sslFile"
		done 
	fi

	echo "    CustomLog \"|/usr/bin/cronolog /mnt/services/${service}/log/access-%Y-%m.log\" common" | sudo tee -a "$sslFile"
	echo "    ErrorLog \"|/usr/bin/cronolog /mnt/services/${service}/log/error-%Y-%m.log\"" | sudo tee -a "$sslFile"
	echo "    ProxyRequests Off" | sudo tee -a "$sslFile"
	echo "    ProxyPreserveHost On" | sudo tee -a "$sslFile"
	echo "    ProxyPass / http://localhost:8080/" | sudo tee -a "$sslFile"
	echo "    <Proxy *>" | sudo tee -a "$sslFile"
	echo "        Order deny,allow" | sudo tee -a "$sslFile"
	echo "        Allow from all" | sudo tee -a "$sslFile"
	echo "    </Proxy>" | sudo tee -a "$sslFile"

	echo "    # SSL Config" | sudo tee -a "$sslFile"
	echo "    <IfModule mod_ssl.c>" | sudo tee -a "$sslFile"
	echo "    SSLCipherSuite DEFAULT" | sudo tee -a "$sslFile"
	echo "    SSLEngine on" | sudo tee -a "$sslFile"
	echo "    SSLCertificateFile $sslCert" | sudo tee -a "$sslFile"
	echo "    SSLCertificateKeyFile $sslKey" | sudo tee -a "$sslFile"
	if [ $# -eq 9 ] ; then
		echo "    SSLCACertificateFile $sslChained" | sudo tee -a "$sslFile"
	fi
	echo "" | sudo tee -a "$sslFile"
	echo "    <Files ~ \"\.(cgi|shtml|phtml|php3?)\$\">" | sudo tee -a "$sslFile"
	echo "        SSLOptions +StdEnvVars" | sudo tee -a "$sslFile"
	echo "    </Files>" | sudo tee -a "$sslFile"
	echo "    <Directory \"/usr/local/www/cgi-bin\">" | sudo tee -a "$sslFile"
	echo "        SSLOptions +StdEnvVars" | sudo tee -a "$sslFile"
	echo "    </Directory>" | sudo tee -a "$sslFile"
	echo " SetEnvIf User-Agent \".*MSIE.*\" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0" | sudo tee -a "$sslFile"
	echo "</IfModule>" | sudo tee -a "$sslFile"
	echo "</VirtualHost>" | sudo tee -a "$sslFile"
fi

if [ ! -f "/etc/apache2/sites-enabled/${service}.conf" ] ; then
	sudo a2ensite ${service}.conf | $LOGGER -t "$logTag"
	sudo a2dissite default-ssl
	sudo service apache2 restart
fi

if [ ! -f "/etc/apache2/sites-enabled/${service}-ssl.conf" ] ; then
	if [ $# -gt 6 ] ; then
		sudo a2ensite ${service}-ssl.conf | $LOGGER -t "$logTag"
		sudo a2dissite default-ssl
		sudo service apache2 restart
	fi
fi

# Configure HaProxy
sudo /enstratus/bin/haproxy-runLb

# Update haproxy

if [ -e "/etc/haproxy.cfg" ]; then
	HAPCFG='/etc/haproxy.cfg'
elif [ -e "/etc/haproxy/haproxy.cfg" ]; then
	HAPCFG='/etc/haproxy/haproxy.cfg'
else
	$LOGGER -t "$logTag" Could not find haproxy config file. This is a fail.
fi

found=0
if grep -q "enStratusConfig" $HAPCFG; then
	found=1
fi

if [ $found = 0 ] ; then
  sudo mv ${HAPCFG}{,.bak}

        sudo bash -c "cat > ${HAPCFG}" << EOM
# count = 0
# enStratusConfig
global  
log 127.0.0.1   local1 notice
#log loghost    local0 info
maxconn 4096
user haproxy
group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    maxconn 2000
    contimeout      5000
    clitimeout      50000
    srvtimeout      50000
       
listen ${service} localhost:8080
    mode http
    stats enable
    stats auth haproxy:enstratus
    balance roundrobin 
    cookie SERVERID insert indirect
    option forwardfor
    option httpclose
EOM
fi

$LOGGER -t "$logTag" Configured HAProxy

sudo /enstratus/bin/haproxy-addService $service $remoteAddress $remotePort $HAPCFG
ret=$?
sleep 5

if [ $ret -ne 0 ] ; then
	$LOGGER -t "$logTag" Add service failed: $ret
	exit 20
fi

$LOGGER -t "$logTag" Added Service

sudo service apache2 reload  2>&1 | $LOGGER -t "$logTag"
sudo update-rc.d apache2 enable 2>&1

ret=$?

if [ $ret -ne 0 ] ; then
	$LOGGER -t "$logTag" Restart Apache failed: $ret
	exit 20
fi

$LOGGER -t "$logTag" Restarted Apache

sudo /etc/init.d/haproxy restart 2>&1 | $LOGGER -t "$logTag"
sudo update-rc.d haproxy enable 2>&1

ret=$?

if [ $ret -ne 0 ] ; then
	$LOGGER -t "$logTag" Restart haproxy failed: $ret
	exit 20
fi

$LOGGER -t "$logTag" Restarted HAProxy
