#!/usr/bin/python

import subprocess
import json
import sys

remoteAddress=sys.argv[1]
pool=sys.argv[2]
nodeString=sys.argv[3]
script=sys.argv[4]

nodeList=json.read(nodeString)
for nodes in nodeList:
    for node in nodes:
        if node.startswith(remoteAddress + ':'):
            subprocess.call(['/enstratus/bin/zeus-buildScript', node, pool, script ]);
            
