#!/bin/bash
# setup-centos - Install useful tools and daemons in Centos/RHEL servers

set -u


PATH=/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin

# VERSIONS TO BE INSTALLED
OSSECVER="2.6"    # OSSEC  http://www.ossec.net/main/downloads
MODJKVER="1.2.35" # mod_jk http://www.apache.org/dist/tomcat/tomcat-connectors/jk/
SRMVER="1.2.11"     # http://sourceforge.net/projects/srm/



function install_ossec() {
echo ""
echo "*********************"
echo "OSSEC installation"
echo "*********************"

	while true
		do
			echo "Please press Y to install OSSEC HIDS anything else to leave"
			read z
			case $z in
				[Yy])
					cd /usr/local/src
					wget http://www.ossec.net/files/ossec-hids-$OSSECVER.tar.gz && tar xzf ossec-hids-$OSSECVER.tar.gz && cd ossec-hids-$OSSECVER && ./install.sh && usermod --groups ossec enstratus
					[ -d /usr/local/src/ossec-hids-${OSSECVER} ] && rm -rf /usr/local/src/ossec-hids-${OSSECVER}
					[ -f /usr/local/src/ossec-hids-${OSSECVER}.tar.gz ] && rm /usr/local/src/ossec-hids-${OSSECVER}.tar.gz
					break;;
				*) echo "ossec was not installed"
					break;;
			esac
		done
# Installation of OSSEC HIDS


}


function installmod_jk() {
# Installation of mod_jk module
echo ""
echo "*********************"
echo "mod_jk installation"
echo "*********************"

cd /usr/local/src
wget http://www.apache.org/dist/tomcat/tomcat-connectors/jk/tomcat-connectors-$MODJKVER-src.tar.gz && tar zxf tomcat-connectors-$MODJKVER-src.tar.gz && cd tomcat-connectors-$MODJKVER-src/native && ./configure -with-apxs=/usr/sbin/apxs && make && make install
rm -rf /usr/local/src/tomcat-connectors-$MODJKVER-src
rm /usr/local/src/tomcat-connectors-$MODJKVER-src.tar.gz

}

function pause() {
	echo ""
	echo ""
 	echo "Press enter to continue: " 
	read -p "$*"
}


function install_tomcat() {
echo ""
echo "*********************"
echo "Tomcat installation"
echo "*********************"
cat<<EOF
I can install Tomcat from the distribution repositories. That will install the Java requirements (OpenJDK) also.
EOF


	while true
		do
			echo "Please press Y to install tomcat, anything else to leave"
			read z
			case $z in
				[Yy])	
					if egrep -q "*5\." /etc/redhat-release ; then
						 yum install -y tomcat5
						 service tomcat5 stop
						 chkconfig tomcat5 off
					elif egrep -q "*6\." /etc/redhat-release ; then
						yum install -y tomcat6
						service tomcat6 stop
						chkconfig tomcat6 off
					fi
					break;;
				*) echo "Tomcat was not installed"
					break;;
			esac
		done

}

function install_apache() {
echo ""
echo "*********************"
echo "Apache installation"
echo "*********************"

cat<<EOF
I can install Apache and the mysql client libs from the distribution repositories. This is useful to try the sample deployments
EOF

	while true
		do
			echo "Please press Y to install Apache MySQL client libs, anything else to leave"
			read z
			case $z in
				[Yy])	
					yum -y install httpd  httpd-devel mysql
					service httpd stop
					chkconfig httpd off
					installmod_jk
					break;;
				*) echo "Apache was not installed"
					break;;
			esac
		done

}



function install_mysql() {
echo ""
echo "*********************"
echo "MySQL installation"
echo "*********************"

cat<<EOF
I can install MySQL server from the distribution repositories. This is useful to try the sample deployments
EOF

	while true
		do
			echo "Please press Y to install MySQL server, anything else to leave"
			read z
			case $z in
				[Yy])	
					yum -y install mysql mysql-server MySQL-python
					service mysqld stop
					chkconfig mysqld off
					break;;
				*) echo "MySQL server was not installed"
					break;;
			esac
		done

}

function install_haproxy() {
echo ""
echo  "*********************"
echo  "HAProxy installation"
echo  "*********************"

cat<<EOF
I can install HAProxy server. This is useful if you want to configure this image as a Load Balancer
Notice that for the installation to success the EPEL repository must be enabled
EOF

	while true
		do
			echo "Please press Y to install HAProxy, anything else to leave"
			read z
			case $z in
				[Yy])	
					yum install -y haproxy
					service haproxy stop
					chkconfig haproxy off
					break;;
				*) echo "HAProxy was not installed"
					break;;
			esac
		done

}

function add_EPEL() {
echo ""
echo "*********************"
echo "EPEL repository"
echo "*********************"
cat<<EOF
The EPEL repositories contain many useful packages that are not in the official repositories
EOF

	while true
		do
			echo "Please press Y to add the EPEL repository, anything else to leave"
			read z
			case $z in
				[Yy])
					if egrep -q "*5\." /etc/redhat-release ; then
						yum repolist enabled | grep -q "^epel" || (wget http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm && rpm -Uvh epel-release-5-4.noarch.rpm && rm -f epel-release-5-4.noarch.rpm )
					elif egrep -q "*6\." /etc/redhat-release ; then
						yum repolist enabled | grep -q "^epel" || rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-5.noarch.rpm 
					fi
					break;;
				*) echo "EPEL repository not added"
					break;;
			esac
		done

}


function install_cronolog() {
echo ""
echo "*********************"
echo "cronolog installation"
echo "*********************"
cat<<EOF
I can install cronolog. That requires the EPEL repository

EOF

	while true
		do
			echo "Please press Y to install cronolog, anything else to leave"
			read z
			case $z in
				[Yy])	
					yum -y install  cronolog
					break;;
				*) echo "cronolog not installed"
					break;;
			esac
		done

}


function install_srm() {
# Installation of Secure Delete tools
echo ""
echo "*********************"
echo "Secure delete installation"
echo "*********************"

cat<<EOF
I will install the Secure rm tool. This is highly recommended to securely delete sensitive information, such as the temporary configuration files Enstratius sends to the agent
EOF

	while true
		do
			echo "Please press Y to install srm, anything else to leave"
			read z
			case $z in
				[Yy])
					cd /usr/local/src
					wget http://downloads.sourceforge.net/project/srm/srm/${SRMVER}/srm-${SRMVER}.tar.bz2
					tar jxf srm-${SRMVER}.tar.bz2
					cd srm-${SRMVER}
					./configure && make && make install
					rm -f /usr/local/src/srm-${SRMVER}.tar.bz2
					rm -rf /usr/local/src/srm-${SRMVER}
					break;;
				*) echo "srm was not installed"
			esac
		done

}


function install_postfix() {
echo ""
echo "*********************"
echo "Postfix installation"
echo "*********************"
cat<<EOF
I can install Postfix as MTA instead of sendmail. I won't configure Postfix for you though
EOF

	while true
		do
			echo "Please press Y to install Postfix, anything else to leave"
			read z
			case $z in
				[Yy])	
					yum -y install postfix && yum remove sendmail 
					service postfix stop
					chkconfig postfix off
					chkconfig sendmail off
					break;;
				*) echo "Postfix was not installed"
					break;;
			esac
		done

}

function install_requirements() {

#Install some basic stuff, that probably it's already installed anyway

yum install -y emacs vim-enhanced vim-common zip unzip bzip2 gzip gcc gcc-c++ make automake sudo

if egrep -q "*5\." /etc/redhat-release ; then
	cd /usr/local/src && wget http://dl.fedoraproject.org/pub/epel/5/i386/python-json-3.4-3.el5.noarch.rpm && rpm -ivh python-json-3.4-3.el5.noarch.rpm && rm -f /usr/local/src/python-json-3.4-3.el5.noarch.rpm
else
	# No equivalent for this package in RH/Centos 6
	:
fi
}


function main() {
echo ""
echo "*********************"
echo "Starting installation"
echo "*********************"
cat<< EOF

This script will install some optional software that might be useful to use some features of the Enstratius agent or go trough the automation examples in our documentation. 
If you prefer not to install it now you can always do it manually in the future
I will ask confirmation for several steps, so stay sharp.
EOF

pause
echo "*********************"
echo "Updating installed packages"
echo "*********************"

yum -y update 
echo "*********************"
echo "Installing support for XFS filesystem"
echo "*********************"
yum install -y xfsprogs 
echo "*********************"
echo "Installing support for encrypted volumes and RAID devices"
echo "*********************"

yum install -y cryptsetup-luks mdadm
echo "*********************"
echo "Checking that the modules required for volume encryption are available"
echo "*********************"
/sbin/modprobe sha256 || echo "Module sha256 could not be loaded. This may be prevent volumen encryption from working"
/sbin/modprobe dm_crypt || echo "Module dm_crypt could not be loaded. This may be prevent volumen encryption from working"

install_requirements
install_tomcat
install_apache
install_mysql
install_postfix
install_ossec
add_EPEL
install_haproxy
install_cronolog
install_srm

echo ""
echo "*********************"
echo "Installation finished"
echo "*********************"

}


main 
