#!/bin/bash

set -u

LOGGER=/enstratus/bin/log
logTag="startProxy"

$LOGGER -t "$logTag" startProxy "$@"

BASENAME=`basename $0`
CUSTOM=/enstratus/custom/bin/${BASENAME}

if [ -x ${CUSTOM} ] ; then
    ${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
    exit $?
fi

if [ -d /usr/local/zeus ] ; then
    export PROXY=zeus
elif [ -f /etc/haproxy.cfg ] ; then
    export PROXY=haproxy
else
    export PROXY=modjk
fi

$LOGGER -t "$logTag" "Adding node using the $PROXY load balancing system."

if [ -x ${CUSTOM}-pre ] ; then
    ${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
    if [ $? != 0 ] ; then
        exit $?
    fi
fi

"/enstratus/bin/${PROXY}-startProxy" "$@"

code=$?
if [ $code -ne 0 ] ; then
    $LOGGER -t "$logTag" "Adding node to load balancer $PROXY failed with code $code"
    exit 21
fi

if [ -x ${CUSTOM}-post ] ; then
    ${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
fi

exit 0
