Vagrant.configure("2") do |config|

  config.vm.synced_folder "../../bin/", "/agent/bin"
  config.vm.synced_folder "../../src/", "/agent/src"
  vagrant_root = File.dirname(__FILE__)
  vagrant_root = File.dirname(vagrant_root)
  config.vm.synced_folder "../../", vagrant_root

  $EXPECTED_VERSION = ENV['DCM_EXPECTED_VERSION'] || "0.9.1-b33be0b4cc1b10329ad8de31d07d62ee75a68283"

  config.vm.define 'default-ubuntu-1004-i386' do |c|
    c.vm.hostname="ubuntu-1004-i386"
    c.vm.box = "opscode-ubuntu-10.04-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04-i386_chef-provisionerless.box"

    $FIRST_PACKAGE_URL = "http://es-pyagent.s3.amazonaws.com/dcm-agent-ubuntu-10.04-i386.deb"
    $UPGRADE_PACKAGE_REPO = "http://dcmagentunstable.s3.amazonaws.com/dcm-agent-ubuntu-10.04-i386-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-ubuntu-1004' do |c|
    c.vm.hostname="ubuntu-1004"
    c.vm.box = "opscode-ubuntu-10.04"
    c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04_chef-provisionerless.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-ubuntu-10.04-amd64.deb"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-ubuntu-10.04-amd64-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end

  end

  config.vm.define 'default-ubuntu-1204' do |c|
    c.vm.hostname="ubuntu-1204"
    c.vm.box = "opscode-ubuntu-12.04"
    c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-ubuntu-12.04-amd64.deb"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-ubuntu-12.04-amd64-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-ubuntu-1204-i386' do |c|
    c.vm.hostname="ubuntu-1204-i386"
    c.vm.box = "opscode-ubuntu-12.04-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10-i386_chef-provisionerless.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-ubuntu-12.04-i386.deb"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-ubuntu-12.04-i386-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-ubuntu-1404' do |c|
    c.vm.hostname="ubuntu-1404"
    c.vm.box = "opscode-ubuntu-14.04"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-ubuntu-14.04-amd64.deb"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-ubuntu-14.04-amd64-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-ubuntu-1404-i386' do |c|
    c.vm.hostname="ubuntu-1404-i386"
    c.vm.box = "default-ubuntu-14.04-i386"
    c.vm.box_url = "https://s3.amazonaws.com/dcmagentboxes/default-ubuntu-1404-i386.agent.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-ubuntu-14.04-i386.deb"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-ubuntu-14.04-i386-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-debian-608' do |c|
    c.vm.hostname="default-debian-608"
    c.vm.box = "default-debian-608"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8_chef-provisionerless.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-debian-6.0-amd64.deb"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-debian-6.0-amd64-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-debian-608-i386' do |c|
    c.vm.hostname="default-debian-608-i386"
    c.vm.box = "default-debian-608-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8-i386_chef-provisionerless.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-debian-6.0-i386.deb"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-debian-6.0-i386-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-debian-75' do |c|
    c.vm.hostname="default-debian-75"
    c.vm.box = "default-debian-75"
    c.vm.box_url = "https://vagrantcloud.com/ffuenf/debian-7.5.0-amd64/version/5/provider/virtualbox.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-debian-7.5-amd64.deb"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-debian-7.5-amd64-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-debian-75-i386' do |c|
    c.vm.hostname="default-debian-75-i386"
    c.vm.box = "default-debian-75-i386"
    c.vm.box_url = "https://vagrantcloud.com/remram/debian-7.5-i386/version/1/provider/virtualbox.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-debian-7.5-i386.deb"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-debian-7.5-i386-0.9.1.deb"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-centos-65-i386' do |c|
    c.vm.box = "opscode-centos-6.5-i386"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5-i386_chef-provisionerless.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-centos-6.5-i386.rpm"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-centos-6.5-i386-0.9.1.rpm"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.define 'default-centos-65' do |c|
    c.vm.box = "opscode-centos-6.5"
    c.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"
    $FIRST_PACKAGE_URL = "https://es-pyagent.s3.amazonaws.com/dcm-agent-centos-6.5-x86_64.rpm"
    $UPGRADE_PACKAGE_REPO = "https://dcmagentunstable.s3.amazonaws.com/dcm-agent-centos-6.5-x86_64-0.9.1.rpm"
    c.vm.provision :shell do |shell|
      shell.inline = "sudo /vagrant/run-auto-upgrade-test.sh $1 $2 $3"
      shell.args = ["#$FIRST_PACKAGE_URL", "#$UPGRADE_PACKAGE_REPO", "#$EXPECTED_VERSION"]
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
end
