#!/bin/bash

set -u

logTag="setupEncryption"
LOGGER=/enstratus/bin/log

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ $# -lt 2 ] ; then
   $LOGGER -t "$logTag" Syntax: setupEncryption RAW_DEVICE KEY_FILE
   exit 1
fi

rawDevice=$1
encryptedDevice=$2
keyFile=$3

$LOGGER -t "$logTag" setupEncryption "$@" 

if [ ! -d "$keyFile" ] ; then
	$LOGGER -t "$logTag" Unable to ready key file
	exit 10
fi

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
	exit $?
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
	if [ $? != 0 ] ; then
		exit $?
	fi
fi

modprobe sha256
if [ $? != 0 ] ; then
	$LOGGER -t "$logTag" No support for SHA256 encryption, cannot encrypt file system for $rawDevice
	exit 80
fi
modprobe dm_crypt
if [ $? != 0 ] ; then
	$LOGGER -t "$logTag" No support for dm_crypt, cannot encrypt file system for $rawDevice"
	exit 81
fi
	
sudo cryptsetup -q luksFormat --cipher aes-cbc-essiv:sha256 "/dev/$rawDevice" "$keyFile" 2>&1 | $LOGGER -t "$logTag"

if [ $? != 0 ] ; then
	$LOGGER -t "$logTag" Unable to setup encryption.
	exit 11
fi

if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
fi

exit 0
