#!/bin/bash

set -u

LOGGER=/enstratus/bin/log
logTag="stopProxy"

$LOGGER -t "$logTag" stopProxy "$@"

if [ $# -lt 1 ] ; then 
	$LOGGER -t "$logTag" Syntax: stopProxy ADDRESS
	exit 1
fi

ipAddress=$1

APACHE=/etc/apache2

if [ -r /mnt/tmp/workers.list ] ; then
	sudo rm -f /mnt/tmp/workers.list
fi

/enstratus/bin/removeAddress $ipAddress /mnt/tmp/workers.list 2>&1 | $LOGGER -t "$logTag"

ret=$?

if [ $ret -ne 0 ] ; then
	$LOGGER -t "$logTag" Removal of address failed: $ret
	exit 20
fi

sudo mv /mnt/tmp/workers.list "$APACHE/workers.list"

sudo bin/buildWorkers "$APACHE/workers.list" "$APACHE/workers.properties" 2>&1 | $LOGGER -t "$logTag"

ret=$?

if [ $ret -ne 0 ] ; then
	$LOGGER -t "$logTag" Rebuild of workers.properties: $ret
	exit 21
fi

sudo /usr/sbin/apache2ctl graceful 2>&1 | $LOGGER -t "$logTag"

ret=$?

if [ $ret -ne 0 ] ; then
	$LOGGER -t "$logTag" Apache restart failed: $ret
	exit 22
fi

if [ -e "/enstratus/custom/bin/removeService" ] ; then
	sudo /enstratus/custom/bin/removeService $service $remoteAddress $remotePort
fi

exit 0
