#!/usr/bin/env bash

# Copyright 2011-2013 Enstratius, Inc.
#
# backupDataSource - Dumps a data source to the specified file location
# 
# This software is part of the Enstratius Cloud Management System. Only 
# authorized licensees of Enstratius may use this software and only
# in the context of Enstratius-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the Enstratius system as needed.
#
# FUNCTION
# Dumps a data source to the specified file location
#

set -u

BASENAME=`basename $0`
DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"

LOGGER=$DIRNAME/log
logTag=backupDataSource

if [ $# -lt 4 ] ; then
   $LOGGER -t "$logTag" "Syntax: backupDataSource SERVICE_ID DATA_SOURCE CONFIG_FILE FILE_PATH"
   exit 1
fi

serviceId=$1
dataSourceName=$2
configFile="$3"
backupFile="$4"

$LOGGER -t "$logTag" backupDataSource "$@"

BACKUP="/mnt/services/$serviceId/bin/enstratus-backupDataSource"

if [ ! -x "$BACKUP" ] ; then
	$LOGGER -t "$logTag" "Unable to find custom backup script ${BACKUP}. Fail."
	exit 10
fi

"$BACKUP" $serviceId $dataSourceName $configFile $backupFile 2>&1 | $LOGGER -t "$logTag"
exit_with_pipe_value
