#!/usr/bin/env bash

set -u

BASENAME=`basename $0`
DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"

logTag="closeEncryption"
LOGGER=$DIRNAME/log

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:$DCM_BASEDIR/bin

BASENAME=`basename $0`

if [ $# -lt 1 ] ; then
   $LOGGER -t "$logTag" Syntax: closeEncryption ENCRYPTED_DEVICE
   exit 1
fi

if ! sudo which cryptsetup ; then
	$LOGGER -t "$logTag" cryptsetup not installed
	exit 2
fi

encryptedDevice=$1

$LOGGER -t "$logTag" closeEncryption "$@"

sudo cryptsetup remove $encryptedDevice > /dev/null 2>&1

if [ $? != 0 ] ; then
        $LOGGER -t "$logTag" Unable to open encrypted device.
        exit 11
fi

exit 0
