#!/usr/bin/env bash

set -u
PATH=/sbin:${PATH}

BASENAME=`basename $0`
DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"

logTag="addUser"
LOGGER=$DIRNAME/log
logTag="configureRaid"

BASENAME=`basename $0`

$LOGGER -t "$logTag" configureRaid "$@"

args=($@)
RAID_LEVEL=$1
deviceId=$2
devices=${args[@]:2}

deviceArray=($devices)
deviceCount=${#deviceArray[*]}

map=""
el_ver=0
if [ -f /etc/redhat-release ]; then
	el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
fi
for d in ${devices}; do
	new_letter=$(echo ${d:(-1)} | tr 'a-z' 'e-z')
	if [ -b /dev/$d ]; then
		device=$d
	elif [ -b /dev/${d/#sd/xvd} ]; then
		device=${d/#sd/xvd}
	elif [[ $el_ver > 6.0 && -b /dev/xvd${new_letter} ]]; then
		device=xvd${new_letter}
	else
		$LOGGER -t "$logTag" "/dev/$d does not seem to exist. Ignoring"
	fi

	map="${map} /dev/${device}"
done

sudo modprobe raid$RAID_LEVEL

#If you encounter problems related to metadata compatibility, try metadata 1.1.
#yes | sudo mdadm --create /dev/$deviceId --level 0 --metadata=1.1 --raid-devices $deviceCount $map > /dev/null 2>&1
yes | sudo /sbin/mdadm --create /dev/$deviceId --level $RAID_LEVEL --raid-devices $deviceCount $map > /dev/null 2>&1
if [ $? != 0 ] ; then
	$LOGGER -t "$logTag" "Unable to create RAID with mdadm."
	exit 20
fi

if [ -f /etc/mdadm/mdadm.conf ] ; then
        echo "DEVICE" $map | sudo tee -a /etc/mdadm/mdadm.conf > /dev/null 2>&1
        sudo mdadm --detail --scan | sudo tee -a /etc/mdadm/mdadm.conf > /dev/null 2>&1
elif [ -f /etc/mdadm.conf ] ; then
        echo "DEVICE" $map | sudo tee -a /etc/mdadm.conf > /dev/null 2>&1 
        sudo mdadm --detail --scan | sudo tee -a /etc/mdadm.conf > /dev/null 2>&1
else    
        echo "DEVICE" $map | sudo tee -a /etc/mdadm.conf > /dev/null 2>&1
        sudo mdadm --detail --scan | sudo tee -a /etc/mdadm.conf > /dev/null 2>&1
fi

exit 0
