#!/usr/bin/env bash

set -u

BASENAME=`basename $0`
DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"

logTag="format"
LOGGER=$DCM_BASEDIR/bin/log

BASENAME=`basename $0`

if [ $# -lt 4 ] ; then
   $LOGGER -t "$logTag" Syntax: format DEVICE_ID FILE_SYSTEM MOUNT_POINT ENCRYPTED
   exit 1
fi

deviceId=$1
fileSystem=$2
mountPoint=$3
encrypted=$4

$LOGGER -t "$logTag" format $@

el_ver=0
if [ -f /etc/redhat-release ]; then
	el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
fi
new_letter=$(echo ${deviceId:(-1)} | tr 'a-z' 'e-z')

if [[ $encrypted == "true" ]] ; then
	device=/dev/mapper/$deviceId
elif [ -b /dev/$deviceId ] ; then
	device=/dev/$deviceId
elif [ -b /dev/${deviceId/#sd/xvd} ] ; then
	device=/dev/${deviceId/#sd/xvd}
elif [[ $el_ver > 6.0 && ! -b /dev/$deviceId && -b /dev/xvd${new_letter} ]]; then
	device=/dev/xvd${new_letter}
else
	$LOGGER -t "$logTag" "Cannot find device ${deviceId}."
	exit 1
fi

if [ ! -f /sbin/mkfs.${fileSystem} ]; then
  $LOGGER -t "$logTag" "${fileSystem} not supported"
  exit 24
fi

case "$fileSystem" in
reiserfs)	yes | sudo /sbin/mkfs.${fileSystem} -f $device
			;;
*)			yes | sudo /sbin/mkfs.${fileSystem} $device
			;;
esac

if [ $? != 0 ] ; then
	exit 24
fi

distro=$DCM_AGENT_PLATFORM_NAME
mp=${mountPoint//\//\\\/}
sudo sed -i "/\s$mp\s/d" /etc/fstab
if [[ $encrypted == "true" ]] ; then
	if [ $distro == "ubuntu" ]; then
		echo "$device $mountPoint $fileSystem noatime,nobootwait 0 0" | sudo tee -a /etc/fstab
	else
		echo "$device $mountPoint $fileSystem noatime 0 0" | sudo tee -a /etc/fstab
	fi
else
	if [ $distro == "ubuntu" ]; then
		echo "$device $mountPoint $fileSystem defaults,nobootwait 0 0" | sudo tee -a /etc/fstab
	else
		echo "$device $mountPoint $fileSystem defaults 0 0" | sudo tee -a /etc/fstab
	fi
fi

exit 0
