#!/usr/bin/env bash

# Copyright 2011-2013 Enstratius, Inc.
#
# grantDatabaseAccess - Grants a client application at a specific IP address access to the named data source
# 
# This software is part of the Enstratius Cloud Management System. Only 
# authorized licensees of Enstratius may use this software and only
# in the context of Enstratius-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the Enstratius system as needed.
#
# FUNCTION
# Triggers a service-specific script for granting database access to a client.

set -u
PATH=/bin:${PATH}

BASENAME=`basename $0`
DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"

LOGGER=$DIRNAME/log
logTag="grantDatabaseAccess"

if [ $# -lt 2 ] ; then
   $LOGGER -t "$logTag" "Syntax: grantDatabaseAccess SERVICE_ID CONFIG_FILE"
   exit 1
fi

serviceId=$1
configFile="$2"

$LOGGER -t "$logTag" "grantDatabaseAccess $serviceId $configFile"

sudo chmod 750 "$configFile"

GRANT="/mnt/services/${serviceId}/bin/enstratus-dbgrant"

if [ ! -x "$GRANT" ] ; then
	if [ -f "$GRANT" ] ; then
		$LOGGER -t "$logTag" "Grant script is not executable."
		exit 10
	fi
	exit 0
fi

${GRANT} $serviceId "$configFile" 2>&1 | $LOGGER -t "$logTag"
exit_with_pipe_value
