#!/usr/bin/env bash

[ -t 0 ] || read PIPEINPUT

tag=""
if [ "X$1" == "X-t" ]; then
    shift
    tag="[$1] "
    shift
fi
msg="${@}"

if [ "X$PIPEINPUT" != "X" ]; then
   if [ "X$msg" != "X" ]; then
       msg="$msg "
   fi
   msg="$msg$PIPEINPUT"
fi

if [ -z $DCM_LOG_FILE ]; then
    echo "$tag[$msg]" 1>&2
else
    if [ ! -e $DCM_LOG_FILE ]; then
        touch $DCM_LOG_FILE
    fi
    echo "$tag[$msg]" >> $DCM_LOG_FILE
fi
