#!/usr/bin/env bash

[ -t 0 ] || read PIPEINPUT

tag=""
if [ "X$1" == "X-t" ]; then
    shift
    tag="[$1] "
    shift
fi
msg="${@}"

if [ "X$PIPEINPUT" != "X" ]; then
   if [ "X$msg" != "X" ]; then
       msg="$msg "
   fi
   msg="$msg$PIPEINPUT"
fi
echo "$tag[$msg]" 1>&2