#!/usr/bin/env bash

function log_line() {
    MSG=$1
    if [ -z $DCM_LOG_FILE ]; then
        echo "$MSG" 1>&2
    else
        if [ ! -e $DCM_LOG_FILE ]; then
            touch $DCM_LOG_FILE
        fi
        echo "$MSG" >> $DCM_LOG_FILE
    fi
}

tag=""
if [ "X$1" == "X-t" ]; then
    shift
    tag="[$1] "
    shift
fi
msg="${@}"

if [ ! -z "$msg" ]; then
    log_line "$tag[${msg}]"
fi

if [ ! -t 0 ]; then
    while read PIPEINPUT;
    do
        log_line "$tag[${PIPEINPUT}]"
    done
fi