#!/usr/bin/env bash

set -u
PATH=/bin:${PATH}

BASENAME=`basename $0`
DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"

logTag="mount"
LOGGER=$DIRNAME/log

BASENAME=`basename $0`

if [ $# -lt 3 ] ; then
   $LOGGER -t "$logTag" Syntax: mount DEVICE_ID FILE_SYSTEM MOUNT_POINT
   exit 1
fi

deviceId=$1
fileSystem=$2
mountPoint=$3

$LOGGER -t "$logTag mount $@"

if [ ! -d "$mountPoint" ] ; then
	sudo mkdir "$mountPoint"
fi

# 1. Some kernels may detect sdX devices as xvdX
# 2. sdh is identified as xvdl since RHEL/CentOS 6.1
el_ver=0
distro=$DCM_AGENT_PLATFORM_NAME
if [ -f /etc/redhat-release ]; then
	el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
fi
new_letter=$(echo ${1:(-1)} | tr 'a-z' 'e-z')

if [ ! -b /dev/$1 ]; then
	if [[ -b /dev/${1/#sd/xvd} ]]; then
		deviceId=${1/#sd/xvd}
	elif [[ $el_ver > 6.0 && -b /dev/xvd${new_letter} ]]; then
		deviceId=xvd${new_letter}
	else
		$LOGGER -t "$logTag" "Cannot find device ${deviceId}."
		exit 1
	fi
fi

exists=$(grep " $mountPoint " /etc/fstab)

# nobootwait option is only needed in Ubuntu.
if [[ $exists == "" ]] && [[ $distro == "ubuntu" ]]; then
	echo "/dev/$deviceId $mountPoint $fileSystem defaults,nobootwait 0 0" | sudo tee -a /etc/fstab
elif [[ $exists == "" ]]; then
	echo "/dev/$deviceId $mountPoint $fileSystem defaults 0 0" | sudo tee -a /etc/fstab
fi

sleep 10
sudo mount "$mountPoint" 2>&1 | $LOGGER -t "$logTag"
ret=$?
if [ $ret -ne 0 ]; then
    echo "Mount failed."
    exit $ret
fi
sudo chown $DCM_USER:$DCM_USER "$mountPoint"  2>&1 | $LOGGER -t "$logTag"
sudo chmod 775 "$mountPoint" 2>&1
ret=$?
				
exit $ret
