#!/usr/bin/env bash

# Copyright 2011-2013 Enstratius, Inc.
#
# removeUser - Removes shell access for the specified user.
# 
# This software is part of the Enstratius Cloud Management System. Only 
# authorized licensees of Enstratius may use this software and only
# in the context of Enstratius-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the Enstratius system as needed.
#

set -u

DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"
BASENAME=`basename $0`

logTag="$BASENAME"
LOGGER=$DIRNAME/log

if [ $# -lt 1 ] ; then
   $LOGGER -t "$logTag" Syntax: removeUser USER_ID
   exit 1
fi

$LOGGER -t "$logTag" removeUser "$@"

USERDEL=/usr/sbin/userdel

if [ -f /usr/sbin/userdel ] ; then
	USERDEL=/usr/sbin/userdel
elif [ -f /usr/local/sbin/userdel ] ; then
	USERDEL=/usr/local/sbin/userdel
else
	$LOGGER -t "$logTag" Could not find user remove command 
	exit 80
fi

BASENAME=`basename $0`

USER_ID=${1}

id "$USER_ID" 2> /dev/null
if [ $? != 0 ] ; then
	exit 0
fi

# Remove the user from sudoers.
if [ -d /etc/sudoers.d/ ]; then
	if [ -f /etc/sudoers.d/${USER_ID} ]; then
		sudo rm /etc/sudoers.d/${USER_ID}
	fi
elif [ -f /etc/sudoers ]; then
	sudo sed -i "/${USER_ID}/d" /etc/sudoers
fi

sudo "$USERDEL" -f -r "$USER_ID" 2>&1 | $LOGGER -t "$logTag"
ret=${PIPESTATUS}

# After running 'userdel -f -r' command, code 12 is normally returned. That's because /var/mail/USER_ID does not exist.
# Since it is not a fatal error but a warning, exit code 12 can be replaced with exit code 0.
if [ $ret -eq 12 ]; then
	exit 0
else
	exit $ret
fi
