#!/usr/bin/env bash

set -u

DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"
BASENAME=`basename $0`

logTag="$BASENAME"
LOGGER=$DIRNAME/log

if [ $# -lt 2 ] ; then
   $LOGGER -t "$logTag" "Syntax: rename NAME LOCAL_IP"
   exit 1
fi

$LOGGER -t "$logTag" rename "$@"

BASENAME=`basename $0`


SCALE=0

IPADDRESS=$2

validatehostname() {
	regex="^(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])$"
	echo -n $1 | egrep -q $regex
	return $?
}

oldhostname=$(hostname)
newhostname=$(echo $1 | tr -Cd "[:alnum:].-" )
if ! validatehostname $newhostname  ; then
	$LOGGER -t "$logTag" "$newhostname is not a valid hostmane"
	exit 1
fi

# For a Dynamic Load Balancer on OpenStack the hostname is already set, but there is no /etc/host entry for it
# and so the startPorxy script fails.
# Added a check to see if there is an /etc/host entry for the ipaddress and hostname passed to the rename script.
# If not then don't exit, continue and add an /etc/host entry
if [ $oldhostname = $newhostname ]; then
       grep -wq "^${IPADDRESS}.*${newhostname}" /etc/hosts
       if [ $? -eq 0 ]; then
               $LOGGER -t "$logTag" "hostname has not changed"
               exit 0
       fi
fi

# Set /etc/hosts file before using sudo (prevent sudo:unable to resolve host)
if grep -q ^$2 /etc/hosts ; then
		sudo sed -i "s/$2.*/$2 $newhostname/g" /etc/hosts
else
		sudo bash -c "echo $2 $newhostname >> /etc/hosts "
fi
$LOGGER -t "$logTag" "hostname updated in /etc/hosts"

# Set hostname and /etc/hostname
sudo hostname $newhostname
sudo bash -c "echo $newhostname > /var/tmp/hostname "
sudo mv /var/tmp/hostname /etc/hostname

# Fix chef client.rb if present
#if [ -f /etc/chef/client.rb ] ; then
#	if grep -q "node_name:"  /etc/chef/client.rb; then
#  		sudo sed -i "s/node_name:.*/node_name: $newhostname/g"  /etc/chef/client.rb
#    fi
#fi

# Handle hostname change for Postfix
if [ -f /etc/postfix/main.cf ]; then
	sudo grep -i "s/$oldhostname/$newhostname" /etc/postfix/main.cf
	sudo /etc/init.d/postfix reload
fi	

if [ -x /etc/init.d/sysklogd ] ; then
    sudo /etc/init.d/sysklogd restart
elif [ -x /etc/init.d/syslog ] ; then
    sudo /etc/init.d/syslog restart
fi

if [ -s /etc/init.d/ossec ] ; then
	sudo /etc/init.d/ossec stop
	sudo /etc/init.d/ossec start
fi

STATUS=$?
exit ${STATUS}
