#!/usr/bin/env bash

# Copyright 2011-2013 Enstratius, Inc.
#
# revokeDatabaseAccess - Revokes database access from a client to a specific data source.
# 
# This software is part of the Enstratius Cloud Management System. Only 
# authorized licensees of Enstratius may use this software and only
# in the context of Enstratius-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the Enstratius system as needed.
#
# FUNCTION
# Triggers any script in the target service for revoking database access.

set -u
PATH=/bin:${PATH}

DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"
BASENAME=`basename $0`

LOGFILE="/mnt/tmp/revokeDatabaseAccess.log"
sudo touch "$LOGFILE"
sudo chmod 660 "$LOGFILE"
sudo chown $DCM_USER:$DCM_USER "$LOGFILE"

if [ $# -lt 2 ] ; then
   echo "Syntax: revokeDatabaseAccess SERVICE_ID CONFIG_FILE" >> "$LOGFILE" 2>&1
   exit 1
fi

serviceId=$1
configFile=$2

REVOKE=$DCM_SERVICES_DIR/${serviceId}/bin/enstratus-dbrevoke

if [ ! -x "$REVOKE" ] ; then
	if [ -f "$REVOKE" ] ; then
		echo "Revoke script is not executable." >> "$LOGFILE" 2>&1
		exit 10
	fi
	exit 0
fi

"$REVOKE" $serviceId "$configFile" >> "$LOGFILE" 2>&1

exit $?
