#!/usr/bin/env bash

set -u

DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"
BASENAME=`basename $0`

logTag="runConfigurationManagement-CHEF"
LOGGER=$DIRNAME/log
FIRST_BOOT='/etc/chef/first-boot.json'

$LOGGER -t "$logTag" runConfigurationManagement-CHEF "$@"
echo "$@" | sudo tee $DCM_TMP_DIR/cm-params.log

if [ $# -lt 6 ] ; then
   $LOGGER -t "$logTag" "Syntax: runConfigurationManagement-CHEF RUN_AS_USER NODE_NAME TOKEN CONFIG_FILE_PATH AUTH_ID ENDPOINT CHEF_ENVIRONMENT"
   exit 1
fi

$LOGGER -t "$logTag" "Running configuration management for Chef..."

RUN_AS_USER=$1
NODE_NAME=$2
TOKEN_FILE_PATH=$3
EXTRA_INFO_FILE_PATH=$4
AUTH_ID=$5
ENDPOINT=$6
CHEF_ENVIRONMENT=$7

CLIENT_RB='/etc/chef/client.rb'

# Check for chef-client
CHEF_CLIENT=`which chef-client`

if [ $? != 0 ]; then
   $LOGGER -t "$logTag" "No chef-client found on system. Installing"
   curl -L http://www.opscode.com/chef/install.sh | sudo bash
   if [ $? != 0 ]; then
	$LOGGER -t "$logTag" "Unable to install Chef automatically"
	exit 1
   fi
   CHEF_CLIENT=`which chef-client`
   if [ $? != 0 ]; then
	$LOGGER -t "$logTag" "Still unable to find chef-client. Failing"
	exit 1
   fi
   $LOGGER -t "$logTag" "Chef-client install successfully"
fi

$LOGGER -t "$logTag" "Chef client found in ${CHEF_CLIENT}"

if [ -d "/etc/chef" ]; then
   $LOGGER -t "$logTag" "Existing chef client directory found"
else
   $LOGGER -t "$logTag" "No /etc/chef dir. Making"
   sudo mkdir /etc/chef
   if [ $? != 0 ]; then
       $LOGGER -t "$logTag" "Failed to make /etc/chef: $?"
   fi
fi

if [ -e "/etc/chef/client.rb" ]; then
   $LOGGER -t "$logTag" "Existing client.rb found. Relocating"
   sudo mv /etc/chef/client.rb /etc/chef/client.rb.orig
fi

$LOGGER -t "$logTag" "Building chef client.rb"
echo "log_level :info" | sudo tee /etc/chef/client.rb
echo "log_location STDOUT" | sudo tee -a /etc/chef/client.rb
echo "chef_server_url \"${ENDPOINT}\"" | sudo tee -a /etc/chef/client.rb
echo "validation_client_name \"${AUTH_ID}\"" | sudo tee -a /etc/chef/client.rb
echo "node_name \"${NODE_NAME}\"" | sudo tee -a /etc/chef/client.rb

sudo cp $TOKEN_FILE_PATH /etc/chef/validation.pem > /dev/null 2>&1
if [ $? != 0 ]; then
   $LOGGER -t "$logTag" "Validation PEM was not there. This shouldn't happen"
   exit 1
fi

sudo cp $EXTRA_INFO_FILE_PATH $FIRST_BOOT > /dev/null 2>&1
if [ $? != 0 ]; then
   $LOGGER -t "$logTag" "Runlist cfg wasn't there. This shouldn't happen"
   exit 1
fi

sudo $CHEF_CLIENT -j $FIRST_BOOT -E $CHEF_ENVIRONMENT -L $DCM_TMP_DIR/enstratus-chefrun.log > /dev/null 2>&1
EXIT=$?

sudo chmod 644 $DCM_TMP_DIR/enstratus-chefrun.log

if [ $EXIT != 0 ]; then
        echo "chef-client run failed: $EXIT" 2>&1 | $LOGGER -t "$logTag"
        while read line; do $LOGGER -t "$logTag" "$line"; done <$DCM_TMP_DIR/enstratus-chefrun.log
        exit 99
fi

while read line; do $LOGGER -t "$logTag" "$line"; done <$DCM_TMP_DIR/enstratus-chefrun.log
sudo rm -f /etc/chef/validation.pem > /dev/null 2>&1

$LOGGER -t "$logTag" "Finished running configuration management for Chef."
