#!/usr/bin/env bash

set -u

DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"
BASENAME=`basename $0`

logTag="secureDelete"
LOGGER=$DIRNAME/bin/log

if [ $# -lt 1 ] ; then
   $LOGGER -t "$logTag" Syntax: secureDelete FILE_NAME
   exit 1
fi

BASENAME=`basename $0`

if [ -x /usr/bin/srm ] ; then
	/usr/bin/srm -f -z "$1"
	EXIT_CODE=$?
elif [ -x /usr/sbin/srm ] ; then
    /usr/sbin/srm -f -z "$1"
    EXIT_CODE=$?
elif [ -x /usr/local/bin/srm ] ; then
    /usr/local/bin/srm -f -z "$1"
    EXIT_CODE=$?
else
	rm -f "$1"
	EXIT_CODE=$?
	if [ $? != 0 ] ; then
		$LOGGER -t "$logTag" Secure delete is not installed on this server. $1 was deleted, but not securely deleted.
	fi
fi

exit $EXIT_CODE

