#!/usr/bin/env bash

set -u

BASENAME=`basename $0`
DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:$DCM_BASEDIR/bin

logTag="setupEncryption"
LOGGER=$DCM_BASEDIR/bin/log

BASENAME=`basename $0`

if [ $# -lt 2 ] ; then
   $LOGGER -t "$logTag" Syntax: setupEncryption RAW_DEVICE KEY_FILE
   exit 1
fi

if ! sudo which cryptsetup ; then
    $LOGGER -t "$logTag" cryptsetup not installed
    exit 2
fi

rawDevice=$1
encryptedDevice=$2
keyFile=$3

$LOGGER -t "$logTag" setupEncryption "$@" 

if [ ! -f "$keyFile" ] ; then
	$LOGGER -t "$logTag" Unable to ready key file
	exit 10
fi

sudo modprobe dm_crypt
if [ $? != 0 ] ; then
	$LOGGER -t "$logTag" "No support for dm_crypt, cannot encrypt file system for $rawDevice"
	exit 81
fi

# initializes a LUKS partition and sets the initial key, either via prompting or via <key file>.
# 1. Some kernels may detect sdX devices as xvdX
# 2. sdh is identified as xvdl since RHEL/CentOS 6.1
el_ver=0
if [ -f /etc/redhat-release ]; then
	el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
fi
new_letter=$(echo ${1:(-1)} | tr 'a-z' 'e-z')

if [ ! -b /dev/$1 ]; then
	if [[ -b /dev/${1/#sd/xvd} ]]; then
		rawDevice=${1/#sd/xvd}
	elif [[ $el_ver > 6.0 && -b /dev/xvd${new_letter} ]]; then
		rawDevice=xvd${new_letter}
	else
		$LOGGER -t "$logTag" "Cannot find device ${rawDevice}."
		exit 1
	fi
fi

sudo cryptsetup -q luksFormat --cipher aes-cbc-essiv:sha256 "/dev/$rawDevice" "$keyFile" > /dev/null 2>&1

if [ $? != 0 ] ; then
	$LOGGER -t "$logTag" Unable to setup encryption.
	exit 11
fi

exit 0
