#!/usr/bin/env bash

set -u

DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"
BASENAME=`basename $0`

LOGGER=$DIRNAME/log
logTag="startProxy"

$LOGGER -t "$logTag" startProxy "$@"

BASENAME=`basename $0`
CUSTOM=$DCM_BASEDIR/custom/bin/${BASENAME}

if [ -x ${CUSTOM} ] ; then
    ${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
    exit_with_pipe_value
fi

if [ -d /usr/local/zeus ] ; then
    export PROXY=zeus
elif [ -f /usr/sbin/haproxy ] ; then
    export PROXY=haproxy
else
    export PROXY=modjk
fi

$LOGGER -t "$logTag" "Adding node using the $PROXY load balancing system."

if [ -x ${CUSTOM}-pre ] ; then
    ${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
    exit_if_pipe_false
fi

"$DCM_BASEDIR/bin/${PROXY}-startProxy" "$@"

code=$?
if [ $code -ne 0 ] ; then
    $LOGGER -t "$logTag" "Adding node to load balancer $PROXY failed with code $code"
    exit 21
fi

if [ -x ${CUSTOM}-post ] ; then
    ${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
    exit_with_pipe_value
fi

exit 0
