#!/usr/bin/env bash

# Copyright 2011-2013 Enstratius Networks, Inc.
#
# terminate - Standard start script that automatically stops all services when the server is going down
# 
# This software is part of the Enstratius Cloud Management System. Only 
# authorized licensees of Enstratius may use this software and only
# in the context of Enstratius-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the Enstratius system as needed.
#

set -u

DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"
BASENAME=`basename $0`

logTag="terminate"
LOGGER=$DIRNAME/log

BASENAME=`basename $0`
CUSTOM=$DCM_BASEDIR/custom/bin/${BASENAME}

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
	exit_if_pipe_false
fi

$LOGGER -t "$logTag" Enstratius is now shutting down the agent.
# XXX TODO fork this out with a delay?
/etc/init.d/dcm-agent stop
