#!/usr/bin/env bash

set -u

DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"
BASENAME=`basename $0`

logTag="terminate"
LOGGER=$DIRNAME/log

BASENAME=`basename $0`

$LOGGER -t "$logTag" Enstratius is now shutting down the agent.
# XXX TODO fork this out with a delay?
/etc/init.d/dcm-agent stop
