#!/usr/bin/env bash

set -u
PATH=/bin:${PATH}

DIRNAME=`dirname $0`
. "$DIRNAME/common_mod"
BASENAME=`basename $0`

logTag="unmount"
LOGGER=$DIRNAME/log

BASENAME=`basename $0`

if [ $# -lt 1 ] ; then
   $LOGGER -t "$logTag" Syntax: unmount MOUNT_POINT
   exit 1
fi

mountPoint=$1

$LOGGER -t "$logTag" unmount "$@" 

sudo umount $mountPoint 2>&1 | $LOGGER -t "$logTag"
				
mp=${mountPoint//\//\\\/}
sudo sed -i "/\s$mp\s/d" /etc/fstab
				
exit 0
