#!/bin/bash

set -u

logTag="format"
LOGGER=/enstratus/bin/log

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

$LOGGER -t "$logTag" $0 $@
$LOGGER -t "$logTag" -v "deviceId: $1, fileSystem: $2, mountPoint: $3, encrypted: $4"

if [ $# -lt 4 ] ; then
   $LOGGER -t "$logTag" Syntax: format DEVICE_ID FILE_SYSTEM MOUNT_POINT ENCRYPTED
   $LOGGER -t "$logTag" "exit 1" at Line \#$LINENO; exit 1
fi

deviceId=$1
fileSystem=$2
mountPoint=$3
encrypted=$4

$LOGGER format $1 $2 $3 $4

if [[ $encrypted == "true" ]] ; then
	device=/dev/mapper/$deviceId
	$LOGGER -t "$logTag" "Encrypted deviced detected."
elif [ -b /dev/$deviceId ] ; then
	device=/dev/$deviceId
elif [ -b /dev/${deviceId/#sd/xvd} ] ; then
	device=/dev/${deviceId/#sd/xvd}
fi

$LOGGER -t "$logTag" "$device detected."

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
	$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
	if [ $? != 0 ] ; then
		$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
	fi
fi

[ -f /sbin/mkfs.${fileSystem} ] || ( $LOGGER -t "$logTag" "${fileSystem} not supported ; exit 24 at Line \#$LINENO" )
case "$fileSystem" in
reiserfs)	yes | sudo /sbin/mkfs.${fileSystem} -f $device
			;;
*)			yes | sudo /sbin/mkfs.${fileSystem} $device
			;;
esac

if [ $? != 0 ] ; then
	$LOGGER -t "$logTag" "exit 24" at Line \#$LINENO; exit 24
fi


mp=${mountPoint//\//\\\/}
sudo sed -i "/\s$mp\s/d" /etc/fstab
if [[ $encrypted == "true" ]] ; then
	echo "$device $mountPoint $fileSystem noatime,nobootwait 0 0" | sudo tee -a /etc/fstab
else
	echo "$device $mountPoint $fileSystem defaults,nobootwait 0 0" | sudo tee -a /etc/fstab
fi

if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
fi

$LOGGER -t "$logTag" "exit 0" at Line \#$LINENO; exit 0
