#!/bin/bash

# Copyright 2011 enStratus Networks LLC
#
# addDataSource - Adds the specified data source to the database service.
# 
# This software is part of the enStratus Cloud Management System. Only 
# authorized licensees of enStratus may use this software and only
# in the context of enStratus-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the enStratus system as needed.
#
# FUNCTION
# Kicks off the database-specific scripts for adding the data source
#

set -u

logTag="installDataSource"
LOGGER=/enstratus/bin/log

$LOGGER -t "$logTag" $0 $@
$LOGGER -t "$logTag" -v "serviceId=$1, configFile=$2, imageFile=$3"

if [ $# -lt 3 ] ; then
   $LOGGER -t "$logTag" "Syntax: installDataSource SERVICE_ID CONFIG_FILE IMAGE_FILE"
   $LOGGER -t "$logTag" "exit 1" at Line \#$LINENO; exit 1
fi

serviceId=$1
configFile="$2"
imageFile="$3"

sudo chmod 750 "$configFile"
sudo chmod 750 "$imageFile"

config_filename=$(basename ${configFile})
image_filename=$(basename ${imageFile})

BACKUP_DIR=/var/log/enstratus/files

# Create a directory for file backup.
if [ ! -d $BACKUP_DIR ]; then
        sudo mkdir -p $BACKUP_DIR
        sudo chown enstratus:enstratus $BACKUP_DIR
fi

# Config file backup for debug.
cp $configFile ${BACKUP_DIR}/${config_filename} && $LOGGER -t "$logTag" "Config file has been copied to ${BACKUP_DIR}/${config_filename} for debug." || $LOGGER -t "$logTag" "Config file backup failed."
cp $imageFile ${BACKUP_DIR}/${image_filename} && $LOGGER -t "$logTag" "Image file has been copied to ${BACKUP_DIR}/${image_filename} for debug." || $LOGGER -t "$logTag" "Image file backup failed."

SCRIPT="/mnt/services/${serviceId}/bin/enstratus-installds"

if [ ! -f "$SCRIPT" ] ; then
	$LOGGER -t "$logTag" "exit 0" at Line \#$LINENO; exit 0
fi

if [ ! -x "$SCRIPT" ] ; then
	$LOGGER -t "$logTag" "$SCRIPT" is not executable.
	$LOGGER -t "$logTag" "exit 22" at Line \#$LINENO; exit 22
fi

${SCRIPT} $serviceId "$configFile" "$imageFile" 2>&1 | $LOGGER -t "$logTag"

$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
