#!/bin/bash

set -u

logTag="upgrade"
LOGGER=/enstratus/bin/log

$LOGGER -t "$logTag" $0 $@

cd /mnt/tmp; tar -xzf enstratus.tar.gz

chmod 750 /mnt/tmp/enstratus/upgrade.sh

nohup /mnt/tmp/enstratus/upgrade.sh &

$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
