#!/bin/bash

set -u

LOGGER=/opt/local/enstratus/bin/log
logTag="modjk:startProxy"

$LOGGER -t "$logTag" startProxy "$@"

service=$1
primaryName=$2
secondaryNames=$3
ipAddress=$4
remoteAddress=$5
remotePort=$6

if [ -z $remoteAddress ] ; then
  exit 0
fi

if [ $# -gt 6 ] ; then
    sslCert=$7
    sslKey=$8
    if [ $# -gt 8 ] ; then
        sslChained=$9
    fi 
fi

APACHE=/opt/local/etc/httpd

if [ ! -d "$APACHE/ssl" ] ; then
    sudo mkdir "$APACHE/ssl"
    sudo chmod 700 "$APACHE/ssl"
fi

if [ $# -gt 6 ] ; then
    sudo mv "$sslCert" "$APACHE/ssl/$service.cert"
    sslCert="$APACHE/ssl/$service.cert"
    sudo mv "$sslKey" "$APACHE/ssl/$service.key"
    sslKey="$APACHE/ssl/$service.key"
    sudo chmod 440 "$sslKey"
    if [ $# -gt 8 ] ; then 
        sudo mv "$sslChained" "$APACHE/ssl/$service.chain"
        sslChained="$APACHE/ssl/$service.chain"
    fi
fi

confFile="${APACHE}/httpd.conf"

if [ ! -f "${confFile}-setup" ] ; then
    echo "ServerName ${ipAddress}" | sudo tee "$confFile"
    cat /opt/local/enstratus/cfg/httpd.conf | sudo tee -a "$confFile"
    echo "NameVirtualHost ${ipAddress}:80" | sudo tee -a "$confFile"
    echo "NameVirtualHost ${ipAddress}:443" | sudo tee -a "$confFile"
    sudo touch "${confFile}-setup"
fi

siteFile="${APACHE}/sites-available/${service}.conf"

echo "<VirtualHost ${ipAddress}:80>" | sudo tee "$siteFile"
echo "    ServerName $primaryName" | sudo tee -a "$siteFile"
if [ $secondaryNames != "NONE" ] ; then
        aliases=$(echo $secondaryNames | tr -s ',' ' ')
        for alias in $aliases ; do
            echo "    ServerAlias $alias" | sudo tee -a "$siteFile"
        done 
fi
echo ""  | sudo tee -a "$siteFile"

echo "    CustomLog \"|/opt/local/sbin/cronolog /var/enstratus/services/${service}/log/access-%Y-%m.log\" common" | sudo tee -a "$siteFile"
echo "    ErrorLog \"|/opt/local/sbin/cronolog /var/enstratus/services/${service}/log/error-%Y-%m.log\"" | sudo tee -a "$siteFile"
echo "    JkMount /* $service" | sudo tee -a "$siteFile"
echo "</VirtualHost>" | sudo tee -a "$siteFile"

sslFile="${APACHE}/sites-available/${service}-ssl.conf"

if [ $# -gt 6 ] ; then
    echo "<VirtualHost ${ipAddress}:443>" | sudo tee "$sslFile"
    echo "    ServerName $primaryName" | sudo tee -a "$sslFile"
    
    if [ $secondaryNames != "NONE" ] ; then
        aliases=$(echo $secondaryNames | tr -s ',' ' ')
        for alias in $aliases ; do
            echo "    ServerAlias $alias" | sudo tee -a "$sslFile"
        done 
    fi
    
    echo "    CustomLog \"|/opt/local/sbin/cronolog /var/enstratus/services/${service}/log/access-%Y-%m.log\" common" | sudo tee -a "$sslFile"
    echo "    ErrorLog \"|/opt/local/sbin/cronolog /var/enstratus/services/${service}/log/error-%Y-%m.log\"" | sudo tee -a "$sslFile"
    echo "    JkMount /* $service" | sudo tee -a "$sslFile"
    echo "" | sudo tee -a "$sslFile"

    echo "    # SSL Config" | sudo tee -a "$sslFile"
    echo "    <IfModule mod_ssl.c>" | sudo tee -a "$sslFile"
    echo "    SSLCipherSuite DEFAULT" | sudo tee -a "$sslFile"
    echo "    SSLEngine on" | sudo tee -a "$sslFile"
    echo "    SSLCertificateFile $sslCert" | sudo tee -a "$sslFile"
    echo "    SSLCertificateKeyFile $sslKey" | sudo tee -a "$sslFile"
    if [ $# -gt 7 ] ; then
        echo "    SSLCACertificateFile $sslChained" | sudo tee -a "$sslFile"
    fi

    echo "" | sudo tee -a "$sslFile"
    echo "    <Files ~ \"\.(cgi|shtml|phtml|php3?)\$\">" | sudo tee -a "$sslFile"
    echo "        SSLOptions +StdEnvVars" | sudo tee -a "$sslFile"
    echo "    </Files>" | sudo tee -a "$sslFile"
    echo "    <Directory \"/usr/local/www/cgi-bin\">" | sudo tee -a "$sslFile"
    echo "        SSLOptions +StdEnvVars" | sudo tee -a "$sslFile"
    echo "    </Directory>" | sudo tee -a "$sslFile"

    echo " SetEnvIf User-Agent \".*MSIE.*\" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0" | sudo tee -a "$sslFile"


    echo "    CustomLog \"|/opt/local/sbin/cronolog /var/enstratus/services/${service}/ssl_request_%Y-%m.log\" common" | sudo tee -a "$sslFile"
    echo "   </IfModule>" | sudo tee -a "$sslFile"
    echo "</VirtualHost>" | sudo tee -a "$sslFile"
fi


if [ -r /var/enstratus/tmp/workers.list ] ; then
    sudo rm -f /var/enstratus/tmp/workers.list
fi

/enstratus/bin/modjk-addAddress $service $remoteAddress $remotePort /var/enstratus/tmp/workers.list 2>&1 | $LOGGER -t "$logTag"

ret=$?

if [ $ret -ne 0 ] ; then
    $LOGGER -t "$logTag" Addition of address failed: $ret
    exit 20
fi

sudo mv /var/enstratus/tmp/workers.list "$APACHE/workers.list"

sudo bin/modjk-buildWorkers "$APACHE/workers.list" "$APACHE/workers.properties" 2>&1 | $LOGGER -t "$logTag"

ret=$?

if [ $ret -ne 0 ] ; then
    $LOGGER -t "$logTag" Rebuild of workers.properties: $ret
    exit 21
fi

if [ ! -f "/opt/local/etc/httpd/sites-enabled/${service}.conf" ] ; then
    sudo ln -s "$siteFile" "/opt/local/etc/httpd/sites-enabled/${service}.conf" 2>&1 | $LOGGER -t "$logTag"
fi

if [ -e "/opt/local/etc/httpd/sites-enabled/${service}-ssl.conf" ] && [! -f "/opt/local/etc/httpd/sites-enabled/${service}-ssl.conf" ] ; then
    if [ $# -gt 6 ] ; then
        sudo ln -s "$sslFile" "/opt/local/etc/httpd/sites-enabled/${service}-ssl.conf" 2>&1 | $LOGGER -t "$logTag"
    fi
fi

sudo svcadm refresh apache 2>&1 | $LOGGER -t "$logTag"

$LOGGER -t "$logTag" Running custom script if available

