#!/usr/bin/env python

import sys
import os

if len(sys.argv) > 1:
	ipAddress=sys.argv[1];
	listFile=sys.argv[2]

	out = open(listFile, 'w');
	if os.path.exists('/opt/local/etc/httpd/workers.list'):
		list = open('/opt/local/etc/httpd/workers.list', 'r')
		for line in list:
			if len(line) > 0:
				parts = line.split(':')
				if len(parts) == 3:
					if parts[1] <> ipAddress:
						out.write(line)
	out.close()
