#!/usr/bin/env python

import sys
import os
import collections

listFile=sys.argv[1]
propsFile=sys.argv[2]

services={}

if os.path.exists(listFile):
	input=open(listFile, 'r')
	for line in input:
		line = line.strip()
		if len(line) > 0:
			parts = line.split(':')
			if len(parts) == 3:
				serviceId=parts[0]
				ipAddress=parts[1]
				proxyPort=parts[2]
				try:
					service=services[serviceId]
				except:
					service=list()
					services[serviceId] = service
				service.append({ 'address' : ipAddress, 'port' : proxyPort })

output=open(propsFile, 'w')
first=True
for serviceId in services:
	if first:
		output.write('worker.list=')
		first = False
	else:
		output.write(',')
	output.write(serviceId)
output.write('\n')
output.flush()
output.write('\n')

for serviceId in services:
	output.write('worker.' + serviceId + '.type=lb\n')
	output.flush()
output.write('\n')

for serviceId in services:
	index=0
	for entry in services[serviceId]:
		index = index + 1
		output.write(('worker.' + serviceId + '-%d.host=' + entry['address'] + '\n') % index)
		output.write(('worker.' + serviceId + '-%d.port=' + entry['port'] + '\n') % index)
		output.write(('worker.' + serviceId + '-%d.type=ajp13\n') % index)
		output.write(('worker.' + serviceId + '-%d.lbfactor=1\n') % index)
		output.write(('worker.' + serviceId + '-%d.socket_timeout=60\n') % index)
		output.flush()
		output.write('\n')
	output.write('worker.' + serviceId + '.balance_workers=')
	for i in range(1,index+1):
		if i <> 1:
			output.write(',')
		output.write(serviceId + '-%d' % i)
    output.write('\n')
output.flush()
output.close()
