#!/bin/bash

set -u

# You must have Java (specifically, Sun's JDK, not the JRE, not some other implementation) pre-installed
# You must set your JAVA_HOME to the directory where that JDK resides
# http://java.sun.com 

yum update -y
yum upgrade -y

yum install -y system-config-date

system-config-date

yum install -y xfsprogs
modprobe sha256
modprobe dm_crypt
echo sha256   >> /etc/modules
echo dm_crypt >> /etc/modules

yum install -y tomcat5
/etc/init.d/tomcat5 stop
chkconfig --del tomcat5

chkconfig --del getsshkey
rm /etc/init.d/getsshkey

yum install -y httpd

yum install -y mod_jk-ap20

yum install -y cronolog

yum install -y emacs

yum install -y mysql-server
chkconfig --del mysqld
rm /etc/init.d/mysqld

yum -y install gcc

cd /mnt/tmp
wget http://mirrors.dotsrc.org/jpackage/1.6/fedora-3/RPMS.free/mod_jk-ap20-1.2.8-1jpp.i386.rpm
rpm -i mod_jk-ap20-1.2.8-1jpp.i386.rpm
rm mod_jk-ap20-1.2.8-1jpp.i386.rpm

wget http://www.ossec.net/files/ossec-hids-2.2.tar.gz
tar -xzf ossec-hids-2.2.tar.gz
cd ossec-hids-2.2
./install.sh
cd ..
rm -r ossec-hids-2.2
rm ossec-hids-2.2.tar.gz

usermod --groups ossec enstratus
