#!/bin/bash

# Copyright 2011 enStratus Networks LLC
#
# grantDatabaseAccess - Grants a client application at a specific IP address access to the named data source
# 
# This software is part of the enStratus Cloud Management System. Only 
# authorized licensees of enStratus may use this software and only
# in the context of enStratus-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the enStratus system as needed.
#
# FUNCTION
# Triggers a service-specific script for granting database access to a client.


set -u

LOGGER=/opt/local/enstratus/bin/log
logTag="grantDatabaseAccess"

if [ $# -lt 2 ] ; then
   $LOGGER -t "$logTag" "Syntax: grantDatabaseAccess SERVICE_ID CONFIG_FILE"
   exit 1
fi

service=$1
configFile="$2"

$LOGGER -t "$logTag" "grantDatabaseAccess $service $configFile"

sudo chmod 750 "$configFile"

GRANT="/mnt/services/${service}/bin/enstratus-dbgrant"

if [ ! -x "$GRANT" ] ; then
	if [ -f "$GRANT" ] ; then
		$LOGGER -t "$logTag" "Grant script is not executable."
		exit 10
	fi
	exit 0
fi

${GRANT} $service "$configFile" 2>&1 | $LOGGER -t "$logTag"

exit $?
