#!/bin/bash

set -u

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ $# -lt 3 ] ; then
   logger -t "$logTag" Syntax: mount DEVICE_ID FILE_SYSTEM MOUNT_POINT
   exit 1
fi

deviceId=$1
fileSystem=$2
mountPoint=$3

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@"
	exit $?
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@"  
	if [ $? != 0 ] ; then
		exit $?
	fi
fi

if [ ! -d "$mountPoint" ] ; then
	sudo mkdir "$mountPoint"
fi

exists=$(grep " $mountPoint " /etc/vfstab)

if [[ $exists == "" ]] ; then
	echo "/dev/$deviceId - $mountPoint $fileSystem - yes -" | sudo tee -a /etc/vfstab
fi

sleep 10
sudo mount "$mountPoint"
sudo chown enstratus:enstratus "$mountPoint"
sudo chmod 775 "$mountPoint"

if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@"
fi

exit 0
