#!/bin/bash

RM=/opt/local/enstratus/bin/secureDelete
CLI=/opt/zeus/zxtm/bin/zcli

remoteAddress="$1"
pool="$2"
script="$3"

if [ -f "${script}.${pool}" ] ; then
    sudo "$RM" "${script}.${pool}"
fi

echo "Pool.getNodes [ \"$pool\" ]" > "${script}.${pool}"

nodes=$(sudo "$CLI" --passfile /etc/zeus.conf/access --json "${script}.${pool}")

/enstratus/bin/zeus-identifyNodes "$remoteAddress" "${pool}" "$nodes" "${script}"

sudo "$RM" "${script}.${pool}"
