#!/bin/bash

set -u

LOGGER=/enstratus/bin/log
logTag="configureRaid"

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"
CONFIGURE_RAID=/tmp/configureRaid.log

$LOGGER -t "$logTag" configureRaid "$@"

args=($@)
deviceId=$1
devices=${args[@]:1}

deviceArray=($devices)
deviceCount=${#deviceArray[*]}

for i in $devices
        do array+=("/dev/"$i)
done

if [ -x ${CUSTOM} ] ; then
        ${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
        exit $?
fi

if [ -x ${CUSTOM}-pre ] ; then
        ${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
        if [ $? != 0 ] ; then
                exit $?
        fi
fi

map=""
el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
for d in ${devices}; do
	new_letter=$(echo ${d:(-1)} | tr 'a-z' 'e-z')
	if [ -b /dev/$d ]; then
		device=$d
	elif [ -b /dev/${d/#sd/xvd} ]; then
		device=${d/#sd/xvd}
	elif [[ $el_ver > 6.0 && -b /dev/xvd${new_letter} ]]; then
		device=xvd${new_letter}
	else
		$LOGGER -t "$logTag" "/dev/$d does not seem to exist. Ignoring"
	fi

	map="${map} /dev/${device}"
done

sudo /sbin/modprobe raid0

yes | sudo /sbin/mdadm --create /dev/$deviceId --level 0 --raid-devices $deviceCount $map > /dev/null 2>&1

if [ $? != 0 ] ; then $LOGGER -t "$logTag" "Unable to create RAID with mdadm." exit 20
fi

if [ -f /etc/mdadm/mdadm.conf ] ; then
        echo "DEVICE" $map | sudo tee -a /etc/mdadm/mdadm.conf > /dev/null 2>&1
        sudo /sbin/mdadm --detail --scan | sudo tee -a /etc/mdadm/mdadm.conf > /dev/null 2>&1
elif [ -f /etc/mdadm.conf ] ; then
        echo "DEVICE" $map | sudo tee -a /etc/mdadm.conf > /dev/null 2>&1 
        sudo /sbin/mdadm --detail --scan | sudo tee -a /etc/mdadm.conf > /dev/null 2>&1
else    
        echo "DEVICE" $map | sudo tee -a /etc/mdadm.conf > /dev/null 2>&1
        sudo /sbin/mdadm --detail --scan | sudo tee -a /etc/mdadm.conf > /dev/null 2>&1
fi

if [ -x ${CUSTOM}-post ] ; then
        ${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
fi

exit 0
