#!/bin/bash

set -u

LOGGER=/enstratus/bin/log
logTag="haproxy:startProxy"

$LOGGER -t "$logTag" startProxy "$@"

service=$1
primaryName=$2
secondaryNames=$3
ipAddress=$4
remoteAddress=$5
remotePort=$6

if [ $# -gt 6 ] ; then
	sslCert=$7
	sslKey=$8
	if [ $# -gt 8 ] ; then
		sslChained=$9
	fi 
fi

# Update haproxy

if [ -e "/etc/haproxy.cfg" ]; then
	HAPCFG='etc/haproxy.cfg'
elif [ -e "/etc/haproxy/haproxy.cfg" ]; then
	HAPCFG='/etc/haproxy/haproxy.cfg'
else
	$LOGGER -t "$logTag" Could not find haproxy config file. This is a fail.
fi

found=0
if grep -q "enStratusConfig" $HAPCFG; then
	found=1
fi

if [ $found = 0 ] ; then
  sudo mv ${HAPCFG}{,.bak}
	sudo bash -c "cat > ${HAPCFG}" << EOM
	# count = 0
	# enStratusConfig
	global  
		log 127.0.0.1   local0
		log 127.0.0.1   local1 notice
		#log loghost    local0 info
		maxconn 4096
		user haproxy
		group haproxy

	defaults
		log     global
		mode    http
		option  httplog
		option  dontlognull
		retries 3
		redispatch
		maxconn 2000
		contimeout      5000
		clitimeout      50000
		srvtimeout      50000
	
	listen ${service} *:$remotePort
		mode http
		stats enable
		stats auth haproxy:enstratus
		balance roundrobin 
		cookie SERVERID insert indirect
		option forwardfor
		option httpclose
	
	# Server Section
EOM

fi

$LOGGER -t "$logTag" Configured HAProxy

sudo /enstratus/bin/haproxy-addService $service $remoteAddress $remotePort $HAPCFG
sleep 5
ret=$?

if [ $ret -ne 0 ] ; then
	$LOGGER -t "$logTag" Add service failed: $ret
	exit 20
fi

$LOGGER -t "$logTag" Added Service

sudo /etc/init.d/haproxy reload 2>&1 | $LOGGER -t "$logTag"

ret=$?

if [ $ret -ne 0 ] ; then
	$LOGGER -t "$logTag" Restart haproxy failed: $ret
	exit 20
fi

$LOGGER -t "$logTag" Restarted HAProxy
