#!/bin/bash

set -u

logTag="mount"
LOGGER=/enstratus/bin/log

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ $# -lt 3 ] ; then
   $LOGGER -t "$logTag" Syntax: mount DEVICE_ID FILE_SYSTEM MOUNT_POINT
   exit 1
fi

deviceId=$1
fileSystem=$2
mountPoint=$3

$LOGGER "$logTag" mount "$@"

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@"  2>&1 | $LOGGER -t "$logTag"
	exit $?
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@"  2>&1 | $LOGGER -t "$logTag"
	if [ $? != 0 ] ; then
		exit $?
	fi
fi

if [ ! -d "$mountPoint" ] ; then
	sudo /bin/mkdir "$mountPoint"
fi

# 1. Some kernels may detect sdX devices as xvdX
# 2. sdh is identified as xvdl since RHEL/CentOS 6.1
el_ver=$(grep -o -E '[0-9]\.[0-9]' /etc/redhat-release)
new_letter=$(echo ${1:(-1)} | tr 'a-z' 'e-z')

if [ ! -b /dev/$1 -a -b /dev/${1/#sd/xvd} ]; then
	deviceId=${1/#sd/xvd}
elif [[ $el_ver > 6.0 && ! -b /dev/$1 && -b /dev/xvd${new_letter} ]]; then
	deviceId=xvd${new_letter}
fi

exists=$(grep " $mountPoint " /etc/fstab)

if [[ $exists == "" ]] ; then
	echo "/dev/$deviceId $mountPoint $fileSystem defaults 0 0" | sudo tee -a /etc/fstab
fi

sleep 10
sudo mount "$mountPoint" 2>&1 | $LOGGER -t "$logTag"
sudo /bin/chown enstratus:enstratus "$mountPoint"  2>&1 | $LOGGER -t "$logTag"
sudo /bin/chmod 775 "$mountPoint" 2>&1 | $LOGGER -t "$logTag"
				
if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
fi

exit 0
