#!/bin/bash

set -u

LOGGER=/enstratus/bin/log
logTag="zeus:stopProxy"

$LOGGER -t "$logTag" startProxy "$@"

RM=/enstratus/bin/secureDelete
CLI=/usr/local/zeus/zxtm/bin/zcli
ESZEUS=/enstratus/bin/zeus

remoteAddress=$1

if [ -z $remoteAddress ] ; then
  exit 0
fi

script="/var/tmp/${remoteAddress}.scr"

if [ -f "$script" ] ; then
    sudo "$RM""$script"
fi

if [ -f "${script}.2" ] ; then
    sudo "$RM" "${script}.2"
fi

echo "Pool.getPoolNames" > "$script"

sudo "$CLI" --passfile /etc/zeus.conf/access --json "$script" | "$ESZEUS-identifyPools" "$remoteAddress" "${script}.2"

sudo "$RM" "$script"

if [ -f "${script}.2" ] ; then
    sudo "$CLI" --passfile /etc/zeus.conf/access "${script}.2"

    sudo "$RM" "${script}.2"
fi

