#!/bin/bash
#
# Perform necessary es-ex-pyagent setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

mkdir -p /enstratus/bin
mkdir -p /enstratus/etc

echo "Thank you for installing es-ex-pyagent!"

exit 0
