#!/bin/bash

logTag="haproxy-addService"
LOGGER=/enstratus/bin/log

$LOGGER -t "$logTag" $0 $@
$LOGGER -t "$logTag" -v "serviceId: $1, remoteAddress: $2, remotePort: $3, HAPCFG: $4"

serviceId=$1
remoteAddress=$2
remotePort=$3
HAPCFG=$4

# Check to see if the address is already listed in the haproxy.cfg
# If it does, just exit.

grep -q "${remoteAddress}" ${HAPCFG}

if [ $? == 0 ] ; then
    $LOGGER -t "$logTag" "exit 0" at Line \#$LINENO; exit 0
fi

count=$( awk '/count/ {print $4}' ${HAPCFG})
incrementCount=$(( $count + 1 ))

sed "s/count = ${count}/count = ${incrementCount}/" -i ${HAPCFG}

echo "        server $serviceId-$incrementCount $remoteAddress:$remotePort cookie $serviceId-$incrementCount check" >> ${HAPCFG}
