#!/bin/bash

# Copyright 2008-2009 enStratus Networks LLC
#
# makeTemp - Shell script to setup the enStratus temp directory
# 
# This software is part of the enStratus Cloud Management System. Only 
# authorized licensees of enStratus may use this software and only
# in the context of enStratus-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the enStratus system as needed.

set -u

logTag="makeTemp"
LOGGER=/enstratus/bin/log

$LOGGER -t "$logTag" $0 $@

if [ ! -d /mnt/tmp ] ; then
	sudo mkdir /mnt/tmp && $LOGGER -t "$logTag" "Temporary directory was created. /mnt/tmp"
	sudo chown enstratus:enstratus /mnt/tmp
	sudo chmod 770 /mnt/tmp
fi

$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
