#!/bin/bash

set -u

LOGGER=/enstratus/bin/log
logTag="modjk:stopProxy"

$LOGGER -t "$logTag" $0 $@
$LOGGER -t "$logTag" -v "ipAddress: $1"

if [ $# -lt 1 ] ; then 
    $LOGGER -t "$logTag" Syntax: stopProxy ADDRESS
    $LOGGER -t "$logTag" "exit 1" at Line \#$LINENO; exit 1
fi

ipAddress=$1

APACHE=/etc/apache2

if [ -r /mnt/tmp/workers.list ] ; then
    sudo rm -f /mnt/tmp/workers.list
fi

/enstratus/bin/modjk-removeAddress $ipAddress /mnt/tmp/workers.list 2>&1 | $LOGGER -t "$logTag"

ret=$?

if [ $ret -ne 0 ] ; then
    $LOGGER -t "$logTag" Removal of address failed: $ret
    $LOGGER -t "$logTag" "exit 20" at Line \#$LINENO; exit 20
fi

sudo mv /mnt/tmp/workers.list "$APACHE/workers.list"

sudo bin/modjk-buildWorkers "$APACHE/workers.list" "$APACHE/workers.properties" 2>&1 | $LOGGER -t "$logTag"

ret=$?

if [ $ret -ne 0 ] ; then
    $LOGGER -t "$logTag" Rebuild of workers.properties: $ret
    $LOGGER -t "$logTag" "exit 21" at Line \#$LINENO; exit 21
fi

sudo /usr/sbin/apache2ctl graceful 2>&1 | $LOGGER -t "$logTag"

ret=$?

if [ $ret -ne 0 ] ; then
    $LOGGER -t "$logTag" Apache restart failed: $ret
    $LOGGER -t "$logTag" "exit 22" at Line \#$LINENO; exit 22
fi

$LOGGER -t "$logTag" "exit 0" at Line \#$LINENO; exit 0
