#!/bin/bash

# Copyright 2011 enStratus Networks LLC
#
# addDataSource - Adds the specified data source to the database service.
# 
# This software is part of the enStratus Cloud Management System. Only 
# authorized licensees of enStratus may use this software and only
# in the context of enStratus-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the enStratus system as needed.
#
# FUNCTION
# Kicks off the database-specific scripts for adding the data source
#

set -u

logTag="installDataSource"
LOGGER=/enstratus/bin/log

if [ $# -lt 3 ] ; then
   $LOGGER -t "$logTag" "Syntax: installDataSource SERVICE_ID CONFIG_FILE IMAGE_FILE"
   exit 1
fi

$LOGGER -t "$logTag" "$@"

service=$1
configFile="$2"
imageFile="$3"

sudo /bin/chmod 750 "$configFile"
sudo /bin/chmod 750 "$imageFile"

SCRIPT="/mnt/services/${service}/bin/enstratus-installds"

if [ ! -f "$SCRIPT" ] ; then
	exit 0
fi

if [ ! -x "$SCRIPT" ] ; then
	$LOGGER -t "$logTag" "$SCRIPT" is not executable.
	exit 22
fi

${SCRIPT} $service "$configFile" "$imageFile" 2>&1 | $LOGGER -t "$logTag"

exit $?
