#!/bin/bash

set -u

logTag="unmount"
LOGGER=/enstratus/bin/log

BASENAME=`basename $0`
CUSTOM="/enstratus/custom/bin/$BASENAME"

if [ $# -lt 1 ] ; then
   $LOGGER -t "$logTag" Syntax: unmount MOUNT_POINT
   exit 1
fi

mountPoint=$1

$LOGGER -t "$logTag" unmount "$@" 

if [ -x ${CUSTOM} ] ; then
	${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
	exit $?
fi

if [ -x ${CUSTOM}-pre ] ; then
	${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
	if [ $? != 0 ] ; then
		exit $?
	fi
fi

sudo /bin/umount $mountPoint 2>&1 | $LOGGER -t "$logTag"
				
if [ -x ${CUSTOM}-post ] ; then
	${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
fi

exit 0
