#!/bin/bash

set -u

EC2_HOME=/usr

logTag="uploadImage"
LOGGER=/enstratus/bin/log

if [ $# -lt 4 ] ; then
   $LOGGER -t "$logTag" "Syntax: uploadImage BUNDLE MANIFEST ACCESS_KEY SECRET_KEY"
   exit 1
fi

$LOGGER -t "$logTag" "Uploading machine image bundle..."

BUNDLE=$1
MANIFEST=$2
ACCESS_KEY=$3
SECRET_KEY=$4
if [ $# -gt 4 ] ; then 
    LOCATION=$5
fi

# This is where enStratus-rolled images live
if [ -x /opt/ec2-ami-tools/current/bin/ec2-bundle-vol ] ; then
	export EC2BIN=/opt/ec2-ami-tools/current/bin
	export EC2_AMITOOL_HOME=/opt/ec2-ami-tools/current
elif [ -x /usr/local/bin/ec2-upload-bundle ] ; then
	export EC2BIN=/usr/local/bin
elif [ -x /home/ec2/bin/ec2-upload-bundle ] ; then
	export EC2BIN=/home/ec2/bin
elif [ -x /opt/aws/amitools/ec2/bin/ec2-upload-bundle ] ; then
        # Amazon Linux
        export EC2_AMITOOL_HOME=/opt/aws/amitools/ec2
        export EC2_HOME=/opt/aws/apitools/ec2
	export EC2BIN=${EC2_AMITOOL_HOME}/bin
else
	export EC2BIN="$EC2_HOME"/bin
fi


if [ $# -gt 4 ] ; then 
    sudo -E ${EC2BIN}/ec2-upload-bundle -b "$BUNDLE" -m "$MANIFEST" -a "$ACCESS_KEY" -s "$SECRET_KEY" --location "$LOCATION" --batch > /mnt/tmp/upload.log 2>&1
else
    sudo -E ${EC2BIN}/ec2-upload-bundle -b "$BUNDLE" -m "$MANIFEST" -a "$ACCESS_KEY" -s "$SECRET_KEY" --batch > /mnt/tmp/upload.log 2>&1
fi

$LOGGER -t "$logTag" "Uploaded."
