#!/bin/bash

# A simple script to get the external ip of an instance. So helpful!
services="ifconfig.me/ip icanhazip.com ipecho.net/plain"
for s in $services
do
	external=$(curl -s $s)
	if echo $external | egrep -q "[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}$" ; then
		echo $external
		exit 0
	fi
done
echo ""
exit 1
