#!/bin/bash

# Copyright 2011 enStratus Networks LLC
#
# backupDataSource - Dumps a data source to the specified file location
# 
# This software is part of the enStratus Cloud Management System. Only 
# authorized licensees of enStratus may use this software and only
# in the context of enStratus-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the enStratus system as needed.
#
# FUNCTION
# Dumps a data source to the specified file location
#

set -u

LOGGER=/enstratus/bin/log
logTag=backupDataSource

$LOGGER -t "$logTag" $0 $@
$LOGGER -t "$logTag" -v "serviceId=$1, dataSourceName=$2, configFile=$3, backupFile=$4" 

if [ $# -lt 4 ] ; then
	$LOGGER -t "$logTag" "Syntax: backupDataSource SERVICE_ID DATA_SOURCE CONFIG_FILE FILE_PATH"
	$LOGGER -t "$logTag" "exit 1" at Line \#$LINENO; exit 1
fi

serviceId=$1
dataSourceName=$2
configFile="$3"
backupFile="$4"

config_filename=$(basename ${configFile})

BACKUP_DIR=/var/log/enstratus/files

# Create a directory for file backup.
if [ ! -d $BACKUP_DIR ]; then
        sudo mkdir -p $BACKUP_DIR
        sudo chown enstratus:enstratus $BACKUP_DIR
fi

# Config file backup for debug.
cp $configFile ${BACKUP_DIR}/${config_filename} && $LOGGER -t "$logTag" "Config file has been copied to ${BACKUP_DIR}/${config_filename} for debug." || $LOGGER -t "$logTag" "Config file backup failed."

$LOGGER -t "$logTag" backupDataSource "$@"

BACKUP="/mnt/services/$serviceId/bin/enstratus-backupDataSource"

if [ ! -x "$BACKUP" ] ; then
	$LOGGER -t "$logTag" "Unable to find custom backup script ${BACKUP}. Fail."
	$LOGGER -t "$logTag" "exit 10" at Line \#$LINENO; exit 10
fi

"$BACKUP" $serviceId $dataSourceName $configFile $backupFile 2>&1 | $LOGGER -t "$logTag"

$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
