#!/bin/bash

logTag="getIpAddress"
LOGGER=/enstratus/bin/log

$LOGGER -t "$logTag" $0 $@

OS=`uname`
IO="" # store IP
case $OS in
   Linux) sudo /sbin/ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}';;
   FreeBSD|OpenBSD) sudo ifconfig  | grep -E 'inet.[0-9]' | grep -v '127.0.0.1' | awk '{ print $2}' ;;
   SunOS) sudo ifconfig -a | grep inet | grep -v '127.0.0.1' | awk '{ print $2} ' ;;
   *) echo "Unknown";;
esac

$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
