#!/bin/bash

# Copyright 2011 enStratus Networks LLC
#
# grantDatabaseAccess - Grants a client application at a specific IP address access to the named data source
# 
# This software is part of the enStratus Cloud Management System. Only 
# authorized licensees of enStratus may use this software and only
# in the context of enStratus-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the enStratus system as needed.
#
# FUNCTION
# Triggers a service-specific script for granting database access to a client.


set -u

LOGGER=/enstratus/bin/log
logTag="grantDatabaseAccess"

$LOGGER -t "$logTag" $0 $@
$LOGGER -t "$logTag" -v "serviceId=$1, configFile=$2"

if [ $# -lt 2 ] ; then
   $LOGGER -t "$logTag" "Syntax: grantDatabaseAccess SERVICE_ID CONFIG_FILE"
   $LOGGER -t "$logTag" "exit 1" at Line \#$LINENO; exit 1
fi

serviceId=$1
configFile="$2"

config_filename=$(basename ${configFile})
BACKUP_DIR=/var/log/enstratus/files

# Create a directory for file backup.
if [ ! -d $BACKUP_DIR ]; then
        sudo mkdir -p $BACKUP_DIR
        sudo chown enstratus:enstratus $BACKUP_DIR
fi

# Config file backup for debug.
cp $configFile ${BACKUP_DIR}/${config_filename} && $LOGGER -t "$logTag" "Config file has been copied to ${BACKUP_DIR}/${config_filename} for debug." || $LOGGER -t "$logTag" "Config file backup failed."

$LOGGER -t "$logTag" "grantDatabaseAccess $serviceId $configFile"
 
sudo chmod 750 "$configFile"

GRANT="/mnt/services/${serviceId}/bin/enstratus-dbgrant"

if [ ! -x "$GRANT" ] ; then
	if [ -f "$GRANT" ] ; then
		$LOGGER -t "$logTag" "Grant script is not executable."
		$LOGGER -t "$logTag" "exit 10" at Line \#$LINENO; exit 10
	fi
	$LOGGER -t "$logTag" "exit 0" at Line \#$LINENO; exit 0
fi

${GRANT} $serviceId "$configFile" 2>&1 | $LOGGER -t "$logTag"

$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
