#!/bin/bash

# This script is called by /enstratus/bin/stopProxy.
# It functions to remove the IP address from the webfarm balanced by
# HA Proxy.

logTag="haproxy-stopProxy"
LOGGER=/enstratus/bin/log

$LOGGER -t "$logTag" $0 $@
$LOGGER -t "$logTag" -v "IPAddress: ${1}"

IP_ADDRESS=${1}

if [ -e "/etc/haproxy.cfg" ]; then
	HAPCFG='etc/haproxy.cfg'
	$LOGGER -t "$logTag" "Found haproxy config file - $HAPCFG"
elif [ -e "/etc/haproxy/haproxy.cfg" ]; then
	HAPCFG='/etc/haproxy/haproxy.cfg'
	$LOGGER -t "$logTag" "Found haproxy config file - $HAPCFG"
else
	$LOGGER -t "$logTag" Could not find haproxy config file. This is a fail.
fi

# Delete the server from the list.
if  grep -q ${IP_ADDRESS} ${HAPCFG}  ; then
	sudo sed -i "/${IP_ADDRESS}/d" ${HAPCFG}
	count=$( awk '/count/ {print $4}' ${HAPCFG})
	incrementCount=$(( $count - 1 ))
	sudo sed "s/count = ${count}/count = ${incrementCount}/" -i ${HAPCFG}
	sudo /etc/init.d/haproxy reload
fi

$LOGGER -t "$logTag" "exit 0" at Line \#$LINENO; exit 0
