#!/bin/bash

# Copyright 2011 enStratus Networks LLC
#
# startService - Starts the specified service
# 
# This software is part of the enStratus Cloud Management System. Only 
# authorized licensees of enStratus may use this software and only
# in the context of enStratus-managed virtual servers and machine images. 
# Unauthorized copying or distribution of this software is strictly prohibited.
# Authorized licensees may copy this software onto any machine images
# and/or virtual hosts being managed by the enStratus system as needed.
#
# FUNCTION
# This script really does nothing except kick-off the service-specific start-up.
#

set -u

LOGGER=/enstratus/bin/log
logTag="startService"

$LOGGER -t "$logTag" $0 $@

if [ $# -lt 1 ] ; then
   $LOGGER -t "$logTag" "Syntax: startService SERVICE_ID"
   exit 1
fi

serviceId=${1}

START="/mnt/services/$serviceId/bin/enstratus-start"

if [ ! -x "$START" ] ; then
	$LOGGER -t "$logTag" "Service start failed for $serviceId - Unable to find custom start script ${START}"
	exit 10
fi

"$START" "$@" 2>&1 | $LOGGER -t "$logTag"

exit $?
