#!/bin/bash

set -u

LOGGER=/enstratus/bin/log
logTag="stopProxy"

$LOGGER -t "$logTag" $0 $@

if [ $# -lt 1 ] ; then 
	$LOGGER -t "$logTag" Syntax: stopProxy ADDRESS
	$LOGGER -t "$logTag" "exit 1" at Line \#$LINENO; exit 1
fi

BASENAME=`basename $0`
CUSTOM=/enstratus/custom/bin/${BASENAME}

if [ -x ${CUSTOM} ] ; then
    ${CUSTOM} "$@" 2>&1 | $LOGGER -t "$logTag"
    $LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
fi

if [ -d /usr/local/zeus ] ; then
    export PROXY=zeus
elif [ -f /usr/sbin/haproxy ] ; then
    export PROXY=haproxy
else
    export PROXY=modjk
fi

$LOGGER -t "$logTag" "Removing mode using the $PROXY load balancing system."

if [ -x ${CUSTOM}-pre ] ; then
    ${CUSTOM}-pre "$@" 2>&1 | $LOGGER -t "$logTag"
    if [ $? != 0 ] ; then
	$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
    fi
fi

"/enstratus/bin/${PROXY}-stopProxy" "$@"

code=$?
if [ $code -ne 0 ] ; then
    $LOGGER -t "$logTag" "Removing node to load balancer $PROXY failed with code $code"
    $LOGGER -t "$logTag" "exit 21" at Line \#$LINENO; exit 21
fi

if [ -x ${CUSTOM}-post ] ; then
    ${CUSTOM}-post "$@" 2>&1 | $LOGGER -t "$logTag"
fi

$LOGGER -t "$logTag" "exit 0" at Line \#$LINENO; exit 0
