#!/bin/bash

set -u

logTag="unlockFileSystems"
LOGGER=/enstratus/bin/log

$LOGGER -t "$logTag" $0 $@
$LOGGER -t "$logTag" "Unlocking XFS file systems..."

systems=$(df -t xfs | awk '{print $6}' | grep -v Mounted)
currentDate=$(date)

for fs in $systems; do
    echo "[$currentDate] unfreeze(xfs) of $fs..." 2>&1 | $LOGGER -t "$logTag"
	sudo xfs_freeze -u "$fs" 2>&1 | $LOGGER -t "$logTag"
done

$LOGGER -t "$logTag" "Unlocked."

$LOGGER -t "$logTag" "exit 0" at Line \#$LINENO; exit 0
