#!/bin/bash


LOGGER=/enstratus/bin/log
logTag="zeus:addSsl"

$LOGGER -t "$logTag" $0 $@
$LOGGER -t "$logTag" -v "ipAddress: $1, service: $2, cert: $3, pk: $4, authority: $5"

CLI=/usr/local/zeus/zxtm/bin/zcli
RM=/enstratus/bin/secureDelete

script="/var/tmp/${service}-ssl"

if [ -f "$script" ] ; then
    sudo "$RM" "$script"
fi

ipAddress=$1
service=$2
cert=$3
pk=$4
if [ $# -gt 4 ] ; then
    authority=$5
    echo "Catalog.SSL.CertificateAuthorities.importCertificateAuthority [ \"${service}-ssl\" ], [ \"${authority}\" ]"
    sudo "$CLI" --passfile /etc/zeus.conf/access "$script"
    sudo "$RM" "$script"
fi 
 
echo "Catalog.SSL.Certificates.importCertificate [ \"${service}-ssl\"], [{ private_key : \"$pk\", public_cert : \"$cert\" } ]" >> "$script"

sudo "$CLI" --passfile /etc/zeus.conf/access "$script"

sudo "$RM" "$script"

echo "VirtualServer.setSSLCertificate [ \"${ipAddress}:443\" ], [ \"${service}-ssl\" ]" > "$script"

sudo "$CLI" --passfile /etc/zeus.conf/access "$script"

sudo "$RM" "$script"

echo "VirtualServer.setSSLDecrypt [ \"${ipAddress}:443\" ], [ true ]" > "$script"

sudo "$CLI" --passfile /etc/zeus.conf/access "$script"

sudo "$RM" "$script"

$LOGGER -t "$logTag" "exit 0" at Line \#$LINENO; exit 0
