#!/bin/bash

RM=/enstratus/bin/secureDelete
CLI=/usr/local/zeus/zxtm/bin/zcli

logTag="zeus-getNodes"
LOGGER=/enstratus/bin/log

$LOGGER -t "$logTag" $0 $@

remoteAddress="$1"
pool="$2"
script="$3"

if [ -f "${script}.${pool}" ] ; then
    sudo "$RM" "${script}.${pool}"
fi

echo "Pool.getNodes [ \"$pool\" ]" > "${script}.${pool}"

nodes=$(sudo "$CLI" --passfile /etc/zeus.conf/access --json "${script}.${pool}")

/enstratus/bin/zeus-identifyNodes "$remoteAddress" "${pool}" "$nodes" "${script}"

sudo "$RM" "${script}.${pool}"

$LOGGER -t "$logTag" "exit $?" at Line \#$LINENO; exit $?
